import { localePacks } from './localePacks';
import { extraLocalePacks } from './extraLocalePacks';

export const supportedLanguages=[
  {code:'en',name:'English'},
  {code:'ka',name:'ქართული'},
  {code:'de',name:'Deutsch'},
  {code:'es',name:'Español'},
  {code:'fr',name:'Français'},
  {code:'pt',name:'Português'},
  {code:'it',name:'Italiano'},
  {code:'ru',name:'Русский'},
  {code:'tr',name:'Türkçe'},
  {code:'el',name:'Ελληνικά'},
  {code:'zh',name:'简体中文'},
  {code:'ja',name:'日本語'},
  {code:'ko',name:'한국어'},
  {code:'ar',name:'العربية'},
  {code:'he',name:'עברית'},
  {code:'hi',name:'हिन्दी'}
] as const;

export type AppLanguage=typeof supportedLanguages[number]['code'];

const languageKey='dealsafe_language';
const languageCodes=new Set<string>(supportedLanguages.map(language=>language.code));
const resolveLanguage=(value:string|null):AppLanguage=>{const normalized=(value||'').toLowerCase();const exact=supportedLanguages.find(language=>language.code===normalized);if(exact)return exact.code;const base=normalized.split('-')[0];return languageCodes.has(base)?base as AppLanguage:'en'};
const storedLanguage=localStorage.getItem(languageKey);
let activeLanguage:AppLanguage=storedLanguage&&languageCodes.has(storedLanguage)?storedLanguage as AppLanguage:resolveLanguage(navigator.languages?.[0]||navigator.language);

const ka:Record<string,string>={
  'Database connected':'მონაცემთა ბაზა დაკავშირებულია','Private beta':'დახურული ბეტა','Sign in':'შესვლა','Sign out':'გასვლა',
  'Dashboard':'მთავარი გვერდი','Activity':'აქტივობა','New deal':'ახალი გარიგება','Create a Deal Link':'გარიგების ბმულის შექმნა',
  'A clearer way to make a private sale':'კერძო გაყიდვის უფრო ნათელი გზა','Put the deal in writing.':'დააფიქსირე გარიგება წერილობით.','Share it with confidence.':'გააზიარე თავდაჯერებულად.',
  'Create a single link with the item, price, parties, and agreed terms—before money or goods change hands.':'შექმენი ერთი ბმული ნივთით, ფასით, მხარეებითა და შეთანხმებული პირობებით — სანამ თანხა ან ნივთი გადაიცემა.',
  'DealSafe does not hold your money in this beta.':'ამ ბეტა ვერსიაში DealSafe თანხას არ ინახავს.','One link. The facts that matter.':'ერთი ბმული. ყველა მნიშვნელოვანი ფაქტი.',
  'Shared terms':'გაზიარებული პირობები','Price, condition, handoff, and disclosures stay together.':'ფასი, მდგომარეობა, გადაცემა და აღწერა ერთ სივრცეში რჩება.',
  'Clear verification':'ნათელი ვერიფიკაცია','See exactly which contact or identity checks are complete.':'ზუსტად ნახე, კონტაქტისა და ვინაობის რომელი შემოწმებაა დასრულებული.',
  'Recorded consent':'დაფიქსირებული თანხმობა','Both parties accept the same version of the agreement.':'ორივე მხარე შეთანხმების ერთსა და იმავე ვერსიას ადასტურებს.',
  'Your workspace':'შენი სამუშაო სივრცე','Recent deals':'ბოლო გარიგებები','Deal dashboard':'გარიგებების მართვა','Track every sale from published link to completed handoff.':'მართე ყველა გაყიდვა ბმულის გამოქვეყნებიდან ნივთის გადაცემამდე.',
  'All deals':'ყველა გარიგება','Active':'აქტიური','Completed':'დასრულებული','Total value':'სრული ღირებულება','Search by item or Deal ID':'მოძებნე ნივთით ან გარიგების ID-ით','No matching deals':'გარიგება ვერ მოიძებნა',
  'Try another search or filter, or create a new Deal Link.':'სცადე სხვა ძიება ან შექმენი ახალი გარიგების ბმული.','Create deal':'გარიგების შექმნა','Selling':'ყიდი','Buying':'ყიდულობ',
  'DealSafe account':'DealSafe ანგარიში','Create your account':'ანგარიშის შექმნა','Welcome back':'კეთილი იყოს დაბრუნება','Your name':'შენი სახელი','Email':'ელფოსტა','Password':'პაროლი','Create account':'ანგარიშის შექმნა',
  'Already have an account? Sign in':'უკვე გაქვს ანგარიში? შედი','New to DealSafe? Create account':'ახალი ხარ DealSafe-ში? შექმენი ანგარიში','Forgot password?':'დაგავიწყდა პაროლი?','Back':'უკან',
  'New Deal Link':'ახალი გარიგების ბმული','Describe what you’re selling':'აღწერე რას ყიდი','You can review every detail before the link is published.':'ბმულის გამოქვეყნებამდე ყველა დეტალს გადაამოწმებ.',
  'Item title':'ნივთის დასახელება','Price (USD)':'ფასი (USD)','Condition':'მდგომარეობა','Known condition and defects':'მდგომარეობა და ცნობილი დეფექტები','Serial or IMEI (optional)':'სერიული ნომერი ან IMEI (არასავალდებულო)','Handoff':'გადაცემის მეთოდი','Publish Deal Link':'გარიგების ბმულის გამოქვეყნება',
  'Item photos or video':'ნივთის ფოტოები ან ვიდეო','Choose photos together or add them one at a time':'აირჩიე ფოტოები ერთად ან დაამატე სათითაოდ','selected':'არჩეულია','Item details':'ნივთის დეტალები','Serial':'სერიული ნომერი','Not provided':'არ არის მითითებული',
  'Seller contact':'გამყიდველის კონტაქტი','Deal agreement':'გარიგების შეთანხმება','The buyer agrees to the stated price, condition disclosures, and handoff method.':'მყიდველი ეთანხმება მითითებულ ფასს, მდგომარეობას და გადაცემის მეთოდს.',
  'Item and defects reviewed':'ნივთი და დეფექტები გადამოწმებულია','Price confirmed':'ფასი დადასტურებულია','Handoff terms confirmed':'გადაცემის პირობები დადასტურებულია','Your full name':'შენი სრული სახელი','Buyer name':'მყიდველის სახელი','Accept these terms':'პირობების მიღება','Terms accepted':'პირობები მიღებულია','verification pending':'ვერიფიკაცია მოლოდინშია',
  'Copy Deal Link':'გარიგების ბმულის კოპირება','Ratings unlock after completion':'შეფასება გაიხსნება დასრულების შემდეგ','One rating per party, tied to this deal.':'თითო შეფასება თითოეული მხარისგან, ამ გარიგებაზე მიბმული.',
  'Agreement copy':'შეთანხმების ასლი','Save or share this record':'შეინახე ან გააზიარე ჩანაწერი','Use your browser’s print screen to save a PDF copy. The live Deal Link remains the current record.':'PDF ასლის შესანახად გამოიყენე ბეჭდვის ფუნქცია. ცოცხალი Deal Link კვლავ მთავარ ჩანაწერად რჩება.','Print / Save PDF':'PDF-ის ბეჭდვა / შენახვა','Share':'გაზიარება',
  'Show QR Code':'QR კოდის ჩვენება','Hide QR Code':'QR კოდის დამალვა','Scan to open this Deal Link on another phone.':'დაასკანერე ამ გარიგების სხვა ტელეფონში გასახსნელად.','Download QR':'QR-ის ჩამოტვირთვა','Preparing QR Code…':'QR კოდი მზადდება…',
  'Trust profile':'ნდობის პროფილი','Average rating':'საშუალო შეფასება','received':'მიღებული','Completed deals':'დასრულებული გარიგებები','Successful handoffs':'წარმატებული გადაცემები','Verification':'ვერიფიკაცია','Identity verification comes next':'შემდეგი ეტაპია ვინაობის ვერიფიკაცია','Reputation history':'რეპუტაციის ისტორია','Member since':'წევრია','No ratings yet':'შეფასებები ჯერ არ არის','Ratings received after completed deals will appear here.':'დასრულებული გარიგებების შეფასებები აქ გამოჩნდება.',
  'Account protection':'ანგარიშის დაცვა','Verification & Security Center':'ვერიფიკაციისა და უსაფრთხოების ცენტრი','Email account active':'ელფოსტა აქტიურია','Identity verification':'ვინაობის ვერიფიკაცია','Request verification':'ვერიფიკაციის მოთხოვნა','Secure handoff enabled':'უსაფრთხო გადაცემა ჩართულია',
  'Account settings':'ანგარიშის პარამეტრები','Manage your account':'ანგარიშის მართვა','Public display name':'საჯარო სახელი','This name appears on your profile and Deal Links.':'ეს სახელი გამოჩნდება პროფილსა და გარიგების ბმულებზე.','Save name':'სახელის შენახვა','Change password':'პაროლის შეცვლა','Use at least 8 characters and keep it private.':'გამოიყენე მინიმუმ 8 სიმბოლო და არავის გაუზიარო.','New password':'ახალი პაროლი','Confirm password':'გაიმეორე პაროლი','Update password':'პაროლის განახლება',
  'all':'ყველა','published':'გამოქვეყნებული','accepted':'მიღებული','completed':'დასრულებული','cancelled':'გაუქმებული','disputed':'გასაჩივრებული','not started':'არ დაწყებულა','pending':'მოლოდინშია','verified':'ვერიფიცირებული','failed':'ვერ შესრულდა',
  'Meet in person':'პირადად შეხვედრა','Ship to buyer':'მყიდველთან გაგზავნა','Like new':'თითქმის ახალი','Good':'კარგი','Fair':'დამაკმაყოფილებელი'
  ,'Creating your Deal Link…':'თქვენი გარიგების ბმული იქმნება…','Item video':'ნივთის ვიდეო','Main photo':'მთავარი ფოტო','Photo':'ფოტო',
  'Seller contact verified':'გამყიდველის კონტაქტი დადასტურებულია','Review agreement':'შეთანხმების ნახვა','At least 8 characters':'მინიმუმ 8 სიმბოლო',
  'Be specific about wear, repairs, locks, and included accessories.':'ზუსტად მიუთითე ცვეთა, შეკეთება, ბლოკირება და თანდართული აქსესუარები.','Stored privately; only last characters shown':'ინახება კონფიდენციალურად; გამოჩნდება მხოლოდ ბოლო სიმბოლოები',
  'Next in production:':'შემდეგი საწარმოო ეტაპი:','Add photos, verify contact, then preview the agreement. This prototype publishes immediately.':'დაამატე ფოტოები, დაადასტურე კონტაქტი და გადახედე შეთანხმებას. ეს პროტოტიპი ბმულს დაუყოვნებლივ აქვეყნებს.',
  'Version':'ვერსია','Buyer':'მყიდველი','Typing your name records consent for this prototype. Production language requires legal review.':'სახელის შეყვანა ამ პროტოტიპში თანხმობას აფიქსირებს. საბოლოო სამართლებრივი ტექსტი იურისტმა უნდა შეამოწმოს.',
  'No written comment.':'წერილობითი კომენტარი არ არის.','Facts, consent, and a clearer handoff.':'ფაქტები, თანხმობა და უფრო ნათელი გადაცემა.'
};

const dictionaries:Record<string,Record<string,string>>=Object.fromEntries(Object.entries(localePacks).map(([code,pack])=>[code,{...pack,...extraLocalePacks[code]}]));
dictionaries.ka={...ka,...extraLocalePacks.ka};
const financeLabels:Record<string,Record<string,string>>={
  en:{Price:'Price',Currency:'Currency'},ka:{Price:'ფასი',Currency:'ვალუტა'},de:{Price:'Preis',Currency:'Währung'},es:{Price:'Precio',Currency:'Moneda'},fr:{Price:'Prix',Currency:'Devise'},pt:{Price:'Preço',Currency:'Moeda'},it:{Price:'Prezzo',Currency:'Valuta'},ru:{Price:'Цена',Currency:'Валюта'},tr:{Price:'Fiyat',Currency:'Para birimi'},el:{Price:'Τιμή',Currency:'Νόμισμα'},zh:{Price:'价格',Currency:'货币'},ja:{Price:'価格',Currency:'通貨'},ko:{Price:'가격',Currency:'통화'},ar:{Price:'السعر',Currency:'العملة'},he:{Price:'מחיר',Currency:'מטבע'},hi:{Price:'कीमत',Currency:'मुद्रा'}
};
Object.entries(financeLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const riskLabels:Record<string,Record<string,string>>={
  en:{'Deal safety check':'Deal safety check','Risk score':'Risk score','Low concern':'Low concern','Review recommended':'Review recommended','Caution':'Caution','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.'},
  ka:{'Deal safety check':'გარიგების უსაფრთხოების შემოწმება','Risk score':'რისკის ქულა','Low concern':'დაბალი რისკი','Review recommended':'რეკომენდებულია გადამოწმება','Caution':'სიფრთხილე','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'ეს ავტომატური შემოწმება იყენებს მხოლოდ DealSafe-ის ჩანაწერში არსებულ მონაცემებს. ის არ არის ბრალდება, გარანტია ან საბაზრო ფასის შეფასება.'},
  de:{'Deal safety check':'Sicherheitsprüfung des Deals','Risk score':'Risikowert','Low concern':'Geringe Bedenken','Review recommended':'Prüfung empfohlen','Caution':'Vorsicht','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Diese automatische Prüfung verwendet nur die Angaben in diesem DealSafe-Eintrag. Sie ist keine Anschuldigung, Garantie oder Marktpreisprüfung.'},
  es:{'Deal safety check':'Comprobación de seguridad','Risk score':'Puntuación de riesgo','Low concern':'Riesgo bajo','Review recommended':'Revisión recomendada','Caution':'Precaución','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Esta comprobación automática solo usa los datos de este registro de DealSafe. No es una acusación, garantía ni comprobación del precio de mercado.'},
  fr:{'Deal safety check':'Contrôle de sécurité','Risk score':'Score de risque','Low concern':'Risque faible','Review recommended':'Vérification recommandée','Caution':'Prudence','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Ce contrôle automatique utilise uniquement les informations de cet enregistrement DealSafe. Il ne constitue ni une accusation, ni une garantie, ni une estimation du prix du marché.'},
  pt:{'Deal safety check':'Verificação de segurança','Risk score':'Pontuação de risco','Low concern':'Risco baixo','Review recommended':'Revisão recomendada','Caution':'Cuidado','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Esta verificação automática utiliza apenas os dados deste registo DealSafe. Não é uma acusação, garantia ou verificação do preço de mercado.'},
  it:{'Deal safety check':'Controllo di sicurezza','Risk score':'Punteggio di rischio','Low concern':'Rischio basso','Review recommended':'Verifica consigliata','Caution':'Attenzione','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Questo controllo automatico usa solo i dati presenti in questo record DealSafe. Non è un’accusa, una garanzia o una verifica del prezzo di mercato.'},
  ru:{'Deal safety check':'Проверка безопасности сделки','Risk score':'Оценка риска','Low concern':'Низкий риск','Review recommended':'Рекомендуется проверка','Caution':'Осторожно','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Автоматическая проверка использует только данные этой записи DealSafe. Это не обвинение, не гарантия и не проверка рыночной цены.'},
  tr:{'Deal safety check':'Anlaşma güvenlik kontrolü','Risk score':'Risk puanı','Low concern':'Düşük risk','Review recommended':'İnceleme önerilir','Caution':'Dikkat','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Bu otomatik kontrol yalnızca bu DealSafe kaydındaki bilgileri kullanır. Bir suçlama, garanti veya piyasa fiyatı kontrolü değildir.'},
  el:{'Deal safety check':'Έλεγχος ασφάλειας συμφωνίας','Risk score':'Βαθμολογία κινδύνου','Low concern':'Χαμηλός κίνδυνος','Review recommended':'Συνιστάται έλεγχος','Caution':'Προσοχή','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Αυτός ο αυτόματος έλεγχος χρησιμοποιεί μόνο τα στοιχεία αυτής της εγγραφής DealSafe. Δεν αποτελεί κατηγορία, εγγύηση ή έλεγχο τιμής αγοράς.'},
  zh:{'Deal safety check':'交易安全检查','Risk score':'风险评分','Low concern':'低风险','Review recommended':'建议核查','Caution':'请谨慎','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'此自动检查仅使用该 DealSafe 记录中的信息，不构成指控、保证或市场价格评估。'},
  ja:{'Deal safety check':'取引の安全チェック','Risk score':'リスクスコア','Low concern':'低リスク','Review recommended':'確認を推奨','Caution':'注意','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'この自動チェックは、このDealSafe記録の情報のみを使用します。告発、保証、市場価格の確認ではありません。'},
  ko:{'Deal safety check':'거래 안전 확인','Risk score':'위험 점수','Low concern':'낮은 위험','Review recommended':'검토 권장','Caution':'주의','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'이 자동 확인은 해당 DealSafe 기록의 정보만 사용합니다. 사기 단정, 보증 또는 시세 확인이 아닙니다.'},
  ar:{'Deal safety check':'فحص سلامة الصفقة','Risk score':'درجة المخاطر','Low concern':'مخاطر منخفضة','Review recommended':'توصى بالمراجعة','Caution':'تنبيه','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'يستخدم هذا الفحص التلقائي تفاصيل سجل DealSafe هذا فقط. وهو ليس اتهامًا أو ضمانًا أو فحصًا لسعر السوق.'},
  he:{'Deal safety check':'בדיקת בטיחות העסקה','Risk score':'ציון סיכון','Low concern':'סיכון נמוך','Review recommended':'מומלץ לבדוק','Caution':'זהירות','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'הבדיקה האוטומטית משתמשת רק בפרטי רשומת DealSafe זו. היא אינה האשמה, הבטחה או בדיקת מחיר שוק.'},
  hi:{'Deal safety check':'डील सुरक्षा जाँच','Risk score':'जोखिम स्कोर','Low concern':'कम जोखिम','Review recommended':'समीक्षा की सलाह','Caution':'सावधानी','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'यह स्वचालित जाँच केवल इस DealSafe रिकॉर्ड की जानकारी का उपयोग करती है। यह आरोप, गारंटी या बाज़ार मूल्य की जाँच नहीं है।'}
};
Object.entries(riskLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const fingerprintLabels:Record<string,Record<string,string>>={
  en:{'Agreement fingerprint':'Agreement fingerprint','Copy fingerprint':'Copy fingerprint','Fingerprint copied.':'Fingerprint copied.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.'},
  ka:{'Agreement fingerprint':'შეთანხმების ციფრული ანაბეჭდი','Copy fingerprint':'ანაბეჭდის კოპირება','Fingerprint copied.':'ანაბეჭდი დაკოპირდა.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'ეს კოდი იცვლება შეთანხმების დეტალების შეცვლისას. ის ასლების შედარებაში გეხმარებათ, მაგრამ კვალიფიციური ელექტრონული ხელმოწერა არ არის.'},
  de:{'Agreement fingerprint':'Digitaler Fingerabdruck der Vereinbarung','Copy fingerprint':'Fingerabdruck kopieren','Fingerprint copied.':'Fingerabdruck kopiert.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Dieser Code ändert sich, wenn sich die Vereinbarung ändert. Er hilft beim Vergleich von Kopien, ist aber keine qualifizierte elektronische Signatur.'},
  es:{'Agreement fingerprint':'Huella digital del acuerdo','Copy fingerprint':'Copiar huella digital','Fingerprint copied.':'Huella digital copiada.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Este código cambia cuando cambian los datos del acuerdo. Ayuda a comparar copias, pero no es una firma electrónica cualificada.'},
  fr:{'Agreement fingerprint':'Empreinte numérique de l’accord','Copy fingerprint':'Copier l’empreinte','Fingerprint copied.':'Empreinte copiée.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Ce code change lorsque les détails de l’accord changent. Il aide à comparer les copies, mais ne constitue pas une signature électronique qualifiée.'},
  pt:{'Agreement fingerprint':'Impressão digital do acordo','Copy fingerprint':'Copiar impressão digital','Fingerprint copied.':'Impressão digital copiada.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Este código muda quando os dados do acordo mudam. Ajuda a comparar cópias, mas não é uma assinatura eletrónica qualificada.'},
  it:{'Agreement fingerprint':'Impronta digitale dell’accordo','Copy fingerprint':'Copia impronta','Fingerprint copied.':'Impronta copiata.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Questo codice cambia quando cambiano i dettagli dell’accordo. Aiuta a confrontare le copie, ma non è una firma elettronica qualificata.'},
  ru:{'Agreement fingerprint':'Цифровой отпечаток соглашения','Copy fingerprint':'Копировать отпечаток','Fingerprint copied.':'Отпечаток скопирован.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Код меняется при изменении условий соглашения. Он помогает сравнивать копии, но не является квалифицированной электронной подписью.'},
  tr:{'Agreement fingerprint':'Anlaşmanın dijital parmak izi','Copy fingerprint':'Parmak izini kopyala','Fingerprint copied.':'Parmak izi kopyalandı.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Anlaşma ayrıntıları değiştiğinde bu kod da değişir. Kopyaları karşılaştırmaya yardımcı olur ancak nitelikli elektronik imza değildir.'},
  el:{'Agreement fingerprint':'Ψηφιακό αποτύπωμα συμφωνίας','Copy fingerprint':'Αντιγραφή αποτυπώματος','Fingerprint copied.':'Το αποτύπωμα αντιγράφηκε.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Αυτός ο κωδικός αλλάζει όταν αλλάζουν οι λεπτομέρειες της συμφωνίας. Βοηθά στη σύγκριση αντιγράφων, αλλά δεν είναι εγκεκριμένη ηλεκτρονική υπογραφή.'},
  zh:{'Agreement fingerprint':'协议数字指纹','Copy fingerprint':'复制数字指纹','Fingerprint copied.':'数字指纹已复制。','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'协议详情发生变化时，此代码也会变化。它可用于比较副本，但不是合格的电子签名。'},
  ja:{'Agreement fingerprint':'契約のデジタル指紋','Copy fingerprint':'指紋をコピー','Fingerprint copied.':'指紋をコピーしました。','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'契約内容が変更されると、このコードも変わります。コピーの比較には役立ちますが、適格電子署名ではありません。'},
  ko:{'Agreement fingerprint':'계약 디지털 지문','Copy fingerprint':'지문 복사','Fingerprint copied.':'지문을 복사했습니다.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'계약 내용이 변경되면 이 코드도 변경됩니다. 사본 비교에 도움이 되지만 공인 전자서명은 아닙니다.'},
  ar:{'Agreement fingerprint':'البصمة الرقمية للاتفاقية','Copy fingerprint':'نسخ البصمة','Fingerprint copied.':'تم نسخ البصمة.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'يتغير هذا الرمز عند تغيير تفاصيل الاتفاقية. يساعد في مقارنة النسخ، لكنه ليس توقيعًا إلكترونيًا مؤهلًا.'},
  he:{'Agreement fingerprint':'טביעת האצבע הדיגיטלית של ההסכם','Copy fingerprint':'העתקת טביעת האצבע','Fingerprint copied.':'טביעת האצבע הועתקה.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'הקוד משתנה כאשר פרטי ההסכם משתנים. הוא מסייע להשוות עותקים, אך אינו חתימה אלקטרונית מאושרת.'},
  hi:{'Agreement fingerprint':'समझौते का डिजिटल फ़िंगरप्रिंट','Copy fingerprint':'फ़िंगरप्रिंट कॉपी करें','Fingerprint copied.':'फ़िंगरप्रिंट कॉपी हो गया।','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'समझौते का विवरण बदलने पर यह कोड बदल जाता है। यह प्रतियों की तुलना में मदद करता है, लेकिन मान्य इलेक्ट्रॉनिक हस्ताक्षर नहीं है।'}
};
Object.entries(fingerprintLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const inviteLabels:Record<string,Record<string,string>>={
  en:{'Invite buyer':'Invite buyer','Share this secure Deal Link with the buyer.':'Share this secure Deal Link with the buyer.','Waiting for buyer':'Waiting for buyer','The buyer must review and accept this agreement from their own account.':'The buyer must review and accept this agreement from their own account.'},
  ka:{'Invite buyer':'მყიდველის მოწვევა','Share this secure Deal Link with the buyer.':'გაუზიარეთ ეს უსაფრთხო Deal Link მყიდველს.','Waiting for buyer':'მყიდველის მოლოდინი','The buyer must review and accept this agreement from their own account.':'მყიდველმა ეს შეთანხმება საკუთარი ანგარიშიდან უნდა განიხილოს და მიიღოს.'},
  de:{'Invite buyer':'Käufer einladen','Share this secure Deal Link with the buyer.':'Diesen sicheren Deal-Link mit dem Käufer teilen.','Waiting for buyer':'Warten auf den Käufer','The buyer must review and accept this agreement from their own account.':'Der Käufer muss diese Vereinbarung in seinem eigenen Konto prüfen und akzeptieren.'},
  es:{'Invite buyer':'Invitar al comprador','Share this secure Deal Link with the buyer.':'Comparte este enlace seguro con el comprador.','Waiting for buyer':'Esperando al comprador','The buyer must review and accept this agreement from their own account.':'El comprador debe revisar y aceptar este acuerdo desde su propia cuenta.'},
  fr:{'Invite buyer':'Inviter l’acheteur','Share this secure Deal Link with the buyer.':'Partagez ce lien sécurisé avec l’acheteur.','Waiting for buyer':'En attente de l’acheteur','The buyer must review and accept this agreement from their own account.':'L’acheteur doit consulter et accepter cet accord depuis son propre compte.'},
  pt:{'Invite buyer':'Convidar o comprador','Share this secure Deal Link with the buyer.':'Partilhe este link seguro com o comprador.','Waiting for buyer':'À espera do comprador','The buyer must review and accept this agreement from their own account.':'O comprador deve rever e aceitar este acordo na sua própria conta.'},
  it:{'Invite buyer':'Invita l’acquirente','Share this secure Deal Link with the buyer.':'Condividi questo link sicuro con l’acquirente.','Waiting for buyer':'In attesa dell’acquirente','The buyer must review and accept this agreement from their own account.':'L’acquirente deve controllare e accettare l’accordo dal proprio account.'},
  ru:{'Invite buyer':'Пригласить покупателя','Share this secure Deal Link with the buyer.':'Отправьте покупателю эту безопасную ссылку на сделку.','Waiting for buyer':'Ожидание покупателя','The buyer must review and accept this agreement from their own account.':'Покупатель должен проверить и принять соглашение из своей учётной записи.'},
  tr:{'Invite buyer':'Alıcıyı davet et','Share this secure Deal Link with the buyer.':'Bu güvenli anlaşma bağlantısını alıcıyla paylaşın.','Waiting for buyer':'Alıcı bekleniyor','The buyer must review and accept this agreement from their own account.':'Alıcı bu anlaşmayı kendi hesabından inceleyip kabul etmelidir.'},
  el:{'Invite buyer':'Πρόσκληση αγοραστή','Share this secure Deal Link with the buyer.':'Μοιραστείτε αυτόν τον ασφαλή σύνδεσμο με τον αγοραστή.','Waiting for buyer':'Αναμονή αγοραστή','The buyer must review and accept this agreement from their own account.':'Ο αγοραστής πρέπει να ελέγξει και να αποδεχτεί τη συμφωνία από τον δικό του λογαριασμό.'},
  zh:{'Invite buyer':'邀请买家','Share this secure Deal Link with the buyer.':'将此安全交易链接分享给买家。','Waiting for buyer':'等待买家','The buyer must review and accept this agreement from their own account.':'买家必须使用自己的账户查看并接受此协议。'},
  ja:{'Invite buyer':'購入者を招待','Share this secure Deal Link with the buyer.':'この安全な取引リンクを購入者と共有してください。','Waiting for buyer':'購入者の確認待ち','The buyer must review and accept this agreement from their own account.':'購入者は自分のアカウントで契約を確認し、同意する必要があります。'},
  ko:{'Invite buyer':'구매자 초대','Share this secure Deal Link with the buyer.':'이 안전한 거래 링크를 구매자와 공유하세요.','Waiting for buyer':'구매자 대기 중','The buyer must review and accept this agreement from their own account.':'구매자는 자신의 계정에서 계약을 검토하고 동의해야 합니다.'},
  ar:{'Invite buyer':'دعوة المشتري','Share this secure Deal Link with the buyer.':'شارك رابط الصفقة الآمن هذا مع المشتري.','Waiting for buyer':'في انتظار المشتري','The buyer must review and accept this agreement from their own account.':'يجب على المشتري مراجعة هذه الاتفاقية وقبولها من حسابه الخاص.'},
  he:{'Invite buyer':'הזמנת הקונה','Share this secure Deal Link with the buyer.':'יש לשתף את קישור העסקה המאובטח עם הקונה.','Waiting for buyer':'ממתינים לקונה','The buyer must review and accept this agreement from their own account.':'הקונה חייב לבדוק ולאשר את ההסכם מהחשבון שלו.'},
  hi:{'Invite buyer':'खरीदार को आमंत्रित करें','Share this secure Deal Link with the buyer.':'यह सुरक्षित डील लिंक खरीदार के साथ साझा करें।','Waiting for buyer':'खरीदार की प्रतीक्षा','The buyer must review and accept this agreement from their own account.':'खरीदार को अपने खाते से इस समझौते की समीक्षा करके इसे स्वीकार करना होगा।'}
};
Object.entries(inviteLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const shareChannelLabels:Record<string,Record<string,string>>={
  en:{'More apps':'More apps','Message copied. Paste it into SMS if needed.':'Message copied. Paste it into SMS if needed.','Sharing is not available. Message copied.':'Sharing is not available. Message copied.'},
  ka:{'More apps':'სხვა აპები','Message copied. Paste it into SMS if needed.':'შეტყობინება დაკოპირდა. საჭიროების შემთხვევაში ჩასვით SMS-ში.','Sharing is not available. Message copied.':'გაზიარება მიუწვდომელია. შეტყობინება დაკოპირდა.'},
  de:{'More apps':'Weitere Apps','Message copied. Paste it into SMS if needed.':'Nachricht kopiert. Bei Bedarf in die SMS einfügen.','Sharing is not available. Message copied.':'Teilen ist nicht verfügbar. Die Nachricht wurde kopiert.'},
  es:{'More apps':'Más aplicaciones','Message copied. Paste it into SMS if needed.':'Mensaje copiado. Pégalo en el SMS si es necesario.','Sharing is not available. Message copied.':'La opción de compartir no está disponible. Se copió el mensaje.'},
  fr:{'More apps':'Plus d’applications','Message copied. Paste it into SMS if needed.':'Message copié. Collez-le dans le SMS si nécessaire.','Sharing is not available. Message copied.':'Le partage n’est pas disponible. Le message a été copié.'},
  pt:{'More apps':'Mais aplicações','Message copied. Paste it into SMS if needed.':'Mensagem copiada. Cole-a no SMS, se necessário.','Sharing is not available. Message copied.':'A partilha não está disponível. A mensagem foi copiada.'},
  it:{'More apps':'Altre app','Message copied. Paste it into SMS if needed.':'Messaggio copiato. Incollalo nell’SMS se necessario.','Sharing is not available. Message copied.':'La condivisione non è disponibile. Il messaggio è stato copiato.'},
  ru:{'More apps':'Другие приложения','Message copied. Paste it into SMS if needed.':'Сообщение скопировано. При необходимости вставьте его в SMS.','Sharing is not available. Message copied.':'Функция отправки недоступна. Сообщение скопировано.'},
  tr:{'More apps':'Diğer uygulamalar','Message copied. Paste it into SMS if needed.':'Mesaj kopyalandı. Gerekirse SMS’e yapıştırın.','Sharing is not available. Message copied.':'Paylaşım kullanılamıyor. Mesaj kopyalandı.'},
  el:{'More apps':'Περισσότερες εφαρμογές','Message copied. Paste it into SMS if needed.':'Το μήνυμα αντιγράφηκε. Επικολλήστε το στο SMS αν χρειάζεται.','Sharing is not available. Message copied.':'Η κοινή χρήση δεν είναι διαθέσιμη. Το μήνυμα αντιγράφηκε.'},
  zh:{'More apps':'更多应用','Message copied. Paste it into SMS if needed.':'消息已复制。如有需要，请粘贴到短信中。','Sharing is not available. Message copied.':'无法使用系统分享。消息已复制。'},
  ja:{'More apps':'その他のアプリ','Message copied. Paste it into SMS if needed.':'メッセージをコピーしました。必要に応じてSMSに貼り付けてください。','Sharing is not available. Message copied.':'共有を利用できません。メッセージをコピーしました。'},
  ko:{'More apps':'다른 앱','Message copied. Paste it into SMS if needed.':'메시지를 복사했습니다. 필요한 경우 SMS에 붙여넣으세요.','Sharing is not available. Message copied.':'공유 기능을 사용할 수 없습니다. 메시지를 복사했습니다.'},
  ar:{'More apps':'تطبيقات أخرى','Message copied. Paste it into SMS if needed.':'تم نسخ الرسالة. ألصقها في الرسالة النصية عند الحاجة.','Sharing is not available. Message copied.':'المشاركة غير متاحة. تم نسخ الرسالة.'},
  he:{'More apps':'אפליקציות נוספות','Message copied. Paste it into SMS if needed.':'ההודעה הועתקה. אפשר להדביק אותה ב-SMS במידת הצורך.','Sharing is not available. Message copied.':'השיתוף אינו זמין. ההודעה הועתקה.'},
  hi:{'More apps':'अन्य ऐप','Message copied. Paste it into SMS if needed.':'संदेश कॉपी हो गया। आवश्यकता होने पर इसे SMS में पेस्ट करें।','Sharing is not available. Message copied.':'शेयर करने की सुविधा उपलब्ध नहीं है। संदेश कॉपी हो गया।'}
};
Object.entries(shareChannelLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const expiryLabels:Record<string,Record<string,string>>={
  en:{'Offer valid for':'Offer valid for','1 day':'1 day','3 days':'3 days','7 days':'7 days','14 days':'14 days','30 days':'30 days','Offer active':'Offer active','Offer expires':'Offer expires','Expired':'Expired','expired':'expired','Deal Link expired':'Deal Link expired','This Deal Link can no longer be accepted.':'This Deal Link can no longer be accepted.','Buyer must accept before this time.':'Buyer must accept before this time.','This Deal Link has expired':'This Deal Link has expired'},
  ka:{'Offer valid for':'შეთავაზების მოქმედების ვადა','1 day':'1 დღე','3 days':'3 დღე','7 days':'7 დღე','14 days':'14 დღე','30 days':'30 დღე','Offer active':'შეთავაზება მოქმედია','Offer expires':'შეთავაზება იწურება','Expired':'ვადა გასულია','expired':'ვადა გასულია','Deal Link expired':'გარიგების ბმულის ვადა გავიდა','This Deal Link can no longer be accepted.':'ამ გარიგების ბმულის მიღება აღარ შეიძლება.','Buyer must accept before this time.':'მყიდველმა ამ დრომდე უნდა მიიღოს პირობები.','This Deal Link has expired':'ამ გარიგების ბმულის ვადა გავიდა'},
  de:{'Offer valid for':'Angebot gültig für','1 day':'1 Tag','3 days':'3 Tage','7 days':'7 Tage','14 days':'14 Tage','30 days':'30 Tage','Offer active':'Angebot aktiv','Offer expires':'Angebot läuft ab','Expired':'Abgelaufen','expired':'abgelaufen','Deal Link expired':'Deal-Link abgelaufen','This Deal Link can no longer be accepted.':'Dieser Deal-Link kann nicht mehr angenommen werden.','Buyer must accept before this time.':'Der Käufer muss vor diesem Zeitpunkt zustimmen.','This Deal Link has expired':'Dieser Deal-Link ist abgelaufen'},
  es:{'Offer valid for':'Oferta válida durante','1 day':'1 día','3 days':'3 días','7 days':'7 días','14 days':'14 días','30 days':'30 días','Offer active':'Oferta activa','Offer expires':'La oferta vence','Expired':'Vencida','expired':'vencida','Deal Link expired':'Enlace de la oferta vencido','This Deal Link can no longer be accepted.':'Este enlace ya no se puede aceptar.','Buyer must accept before this time.':'El comprador debe aceptar antes de esta fecha.','This Deal Link has expired':'Este enlace ha vencido'},
  fr:{'Offer valid for':'Offre valable pendant','1 day':'1 jour','3 days':'3 jours','7 days':'7 jours','14 days':'14 jours','30 days':'30 jours','Offer active':'Offre active','Offer expires':'L’offre expire','Expired':'Expirée','expired':'expirée','Deal Link expired':'Lien de l’offre expiré','This Deal Link can no longer be accepted.':'Ce lien ne peut plus être accepté.','Buyer must accept before this time.':'L’acheteur doit accepter avant cette date.','This Deal Link has expired':'Ce lien a expiré'},
  pt:{'Offer valid for':'Oferta válida por','1 day':'1 dia','3 days':'3 dias','7 days':'7 dias','14 days':'14 dias','30 days':'30 dias','Offer active':'Oferta ativa','Offer expires':'A oferta termina','Expired':'Expirada','expired':'expirada','Deal Link expired':'Link da oferta expirado','This Deal Link can no longer be accepted.':'Este link já não pode ser aceite.','Buyer must accept before this time.':'O comprador deve aceitar antes desta data.','This Deal Link has expired':'Este link expirou'},
  it:{'Offer valid for':'Offerta valida per','1 day':'1 giorno','3 days':'3 giorni','7 days':'7 giorni','14 days':'14 giorni','30 days':'30 giorni','Offer active':'Offerta attiva','Offer expires':'L’offerta scade','Expired':'Scaduta','expired':'scaduta','Deal Link expired':'Link dell’offerta scaduto','This Deal Link can no longer be accepted.':'Questo link non può più essere accettato.','Buyer must accept before this time.':'L’acquirente deve accettare prima di questa data.','This Deal Link has expired':'Questo link è scaduto'},
  ru:{'Offer valid for':'Срок действия предложения','1 day':'1 день','3 days':'3 дня','7 days':'7 дней','14 days':'14 дней','30 days':'30 дней','Offer active':'Предложение активно','Offer expires':'Предложение истекает','Expired':'Срок истёк','expired':'срок истёк','Deal Link expired':'Срок ссылки истёк','This Deal Link can no longer be accepted.':'Эту ссылку на сделку больше нельзя принять.','Buyer must accept before this time.':'Покупатель должен принять условия до этого времени.','This Deal Link has expired':'Срок действия этой ссылки истёк'},
  tr:{'Offer valid for':'Teklif geçerlilik süresi','1 day':'1 gün','3 days':'3 gün','7 days':'7 gün','14 days':'14 gün','30 days':'30 gün','Offer active':'Teklif aktif','Offer expires':'Teklifin bitişi','Expired':'Süresi doldu','expired':'süresi doldu','Deal Link expired':'Anlaşma bağlantısının süresi doldu','This Deal Link can no longer be accepted.':'Bu anlaşma bağlantısı artık kabul edilemez.','Buyer must accept before this time.':'Alıcı bu zamandan önce kabul etmelidir.','This Deal Link has expired':'Bu anlaşma bağlantısının süresi doldu'},
  el:{'Offer valid for':'Ισχύς προσφοράς','1 day':'1 ημέρα','3 days':'3 ημέρες','7 days':'7 ημέρες','14 days':'14 ημέρες','30 days':'30 ημέρες','Offer active':'Ενεργή προσφορά','Offer expires':'Η προσφορά λήγει','Expired':'Έληξε','expired':'έληξε','Deal Link expired':'Ο σύνδεσμος έληξε','This Deal Link can no longer be accepted.':'Αυτός ο σύνδεσμος δεν μπορεί πλέον να γίνει αποδεκτός.','Buyer must accept before this time.':'Ο αγοραστής πρέπει να αποδεχτεί πριν από αυτή την ώρα.','This Deal Link has expired':'Αυτός ο σύνδεσμος έχει λήξει'},
  zh:{'Offer valid for':'报价有效期','1 day':'1天','3 days':'3天','7 days':'7天','14 days':'14天','30 days':'30天','Offer active':'报价有效','Offer expires':'报价到期时间','Expired':'已过期','expired':'已过期','Deal Link expired':'交易链接已过期','This Deal Link can no longer be accepted.':'此交易链接已无法接受。','Buyer must accept before this time.':'买家必须在此时间之前接受。','This Deal Link has expired':'此交易链接已过期'},
  ja:{'Offer valid for':'オファーの有効期間','1 day':'1日','3 days':'3日','7 days':'7日','14 days':'14日','30 days':'30日','Offer active':'オファーは有効です','Offer expires':'有効期限','Expired':'期限切れ','expired':'期限切れ','Deal Link expired':'取引リンクは期限切れです','This Deal Link can no longer be accepted.':'この取引リンクはもう承認できません。','Buyer must accept before this time.':'購入者はこの時刻までに承認する必要があります。','This Deal Link has expired':'この取引リンクは期限切れです'},
  ko:{'Offer valid for':'제안 유효 기간','1 day':'1일','3 days':'3일','7 days':'7일','14 days':'14일','30 days':'30일','Offer active':'제안 활성','Offer expires':'제안 만료','Expired':'만료됨','expired':'만료됨','Deal Link expired':'거래 링크 만료','This Deal Link can no longer be accepted.':'이 거래 링크는 더 이상 수락할 수 없습니다.','Buyer must accept before this time.':'구매자는 이 시간 전에 수락해야 합니다.','This Deal Link has expired':'이 거래 링크가 만료되었습니다'},
  ar:{'Offer valid for':'مدة صلاحية العرض','1 day':'يوم واحد','3 days':'3 أيام','7 days':'7 أيام','14 days':'14 يومًا','30 days':'30 يومًا','Offer active':'العرض ساري','Offer expires':'ينتهي العرض','Expired':'منتهي','expired':'منتهي','Deal Link expired':'انتهت صلاحية رابط الصفقة','This Deal Link can no longer be accepted.':'لم يعد من الممكن قبول رابط الصفقة هذا.','Buyer must accept before this time.':'يجب على المشتري القبول قبل هذا الوقت.','This Deal Link has expired':'انتهت صلاحية رابط الصفقة هذا'},
  he:{'Offer valid for':'תוקף ההצעה','1 day':'יום אחד','3 days':'3 ימים','7 days':'7 ימים','14 days':'14 ימים','30 days':'30 ימים','Offer active':'ההצעה פעילה','Offer expires':'ההצעה תפוג','Expired':'פג תוקף','expired':'פג תוקף','Deal Link expired':'פג תוקף קישור העסקה','This Deal Link can no longer be accepted.':'לא ניתן עוד לאשר את קישור העסקה הזה.','Buyer must accept before this time.':'הקונה חייב לאשר לפני מועד זה.','This Deal Link has expired':'פג תוקף קישור העסקה הזה'},
  hi:{'Offer valid for':'ऑफ़र की वैधता','1 day':'1 दिन','3 days':'3 दिन','7 days':'7 दिन','14 days':'14 दिन','30 days':'30 दिन','Offer active':'ऑफ़र सक्रिय है','Offer expires':'ऑफ़र समाप्त होगा','Expired':'समाप्त','expired':'समाप्त','Deal Link expired':'डील लिंक समाप्त हो गया','This Deal Link can no longer be accepted.':'इस डील लिंक को अब स्वीकार नहीं किया जा सकता।','Buyer must accept before this time.':'खरीदार को इस समय से पहले स्वीकार करना होगा।','This Deal Link has expired':'यह डील लिंक समाप्त हो गया है'}
};
Object.entries(expiryLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const titleValidationLabels:Record<string,Record<string,string>>={
  en:{'Item title must contain 3 to 120 characters.':'Item title must contain 3 to 120 characters.'},
  ka:{'Item title must contain 3 to 120 characters.':'ნივთის დასახელება უნდა შეიცავდეს 3-დან 120 სიმბოლომდე.'},
  de:{'Item title must contain 3 to 120 characters.':'Der Artikeltitel muss 3 bis 120 Zeichen enthalten.'},
  es:{'Item title must contain 3 to 120 characters.':'El título del artículo debe tener entre 3 y 120 caracteres.'},
  fr:{'Item title must contain 3 to 120 characters.':'Le titre de l’article doit contenir entre 3 et 120 caractères.'},
  pt:{'Item title must contain 3 to 120 characters.':'O título do artigo deve ter entre 3 e 120 caracteres.'},
  it:{'Item title must contain 3 to 120 characters.':'Il titolo dell’articolo deve contenere da 3 a 120 caratteri.'},
  ru:{'Item title must contain 3 to 120 characters.':'Название товара должно содержать от 3 до 120 символов.'},
  tr:{'Item title must contain 3 to 120 characters.':'Ürün başlığı 3 ile 120 karakter arasında olmalıdır.'},
  el:{'Item title must contain 3 to 120 characters.':'Ο τίτλος του αντικειμένου πρέπει να περιέχει από 3 έως 120 χαρακτήρες.'},
  zh:{'Item title must contain 3 to 120 characters.':'商品标题必须包含 3 到 120 个字符。'},
  ja:{'Item title must contain 3 to 120 characters.':'商品タイトルは3文字以上120文字以内で入力してください。'},
  ko:{'Item title must contain 3 to 120 characters.':'상품 제목은 3자 이상 120자 이하여야 합니다.'},
  ar:{'Item title must contain 3 to 120 characters.':'يجب أن يتراوح عنوان العنصر بين 3 و120 حرفًا.'},
  he:{'Item title must contain 3 to 120 characters.':'כותרת הפריט חייבת להכיל בין 3 ל-120 תווים.'},
  hi:{'Item title must contain 3 to 120 characters.':'वस्तु का शीर्षक 3 से 120 अक्षरों के बीच होना चाहिए।'}
};
Object.entries(titleValidationLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const createReviewLabels:Record<string,Record<string,string>>={
  en:{'Review before publishing':'Review before publishing','Check every detail before creating the public Deal Link.':'Check every detail before creating the public Deal Link.','No media selected':'No media selected','The Deal Link is not public until you confirm.':'The Deal Link is not public until you confirm.','Confirm and publish':'Confirm and publish','Review deal':'Review deal'},
  ka:{'Review before publishing':'გადაამოწმეთ გამოქვეყნებამდე','Check every detail before creating the public Deal Link.':'საჯარო Deal Link-ის შექმნამდე გადაამოწმეთ ყველა დეტალი.','No media selected':'ფოტო ან ვიდეო არჩეული არ არის','The Deal Link is not public until you confirm.':'თქვენს დადასტურებამდე Deal Link საჯარო არ გახდება.','Confirm and publish':'დადასტურება და გამოქვეყნება','Review deal':'გარიგების გადამოწმება'},
  de:{'Review before publishing':'Vor der Veröffentlichung prüfen','Check every detail before creating the public Deal Link.':'Prüfen Sie alle Angaben, bevor der öffentliche Deal-Link erstellt wird.','No media selected':'Keine Medien ausgewählt','The Deal Link is not public until you confirm.':'Der Deal-Link wird erst nach Ihrer Bestätigung öffentlich.','Confirm and publish':'Bestätigen und veröffentlichen','Review deal':'Deal prüfen'},
  es:{'Review before publishing':'Revisar antes de publicar','Check every detail before creating the public Deal Link.':'Revise todos los detalles antes de crear el enlace público de la operación.','No media selected':'No se seleccionaron archivos','The Deal Link is not public until you confirm.':'El enlace no será público hasta que lo confirme.','Confirm and publish':'Confirmar y publicar','Review deal':'Revisar operación'},
  fr:{'Review before publishing':'Vérifier avant publication','Check every detail before creating the public Deal Link.':'Vérifiez chaque détail avant de créer le lien public de la transaction.','No media selected':'Aucun média sélectionné','The Deal Link is not public until you confirm.':'Le lien ne devient public qu’après votre confirmation.','Confirm and publish':'Confirmer et publier','Review deal':'Vérifier la transaction'},
  pt:{'Review before publishing':'Rever antes de publicar','Check every detail before creating the public Deal Link.':'Reveja todos os detalhes antes de criar o link público da transação.','No media selected':'Nenhum ficheiro selecionado','The Deal Link is not public until you confirm.':'O link só será público depois da sua confirmação.','Confirm and publish':'Confirmar e publicar','Review deal':'Rever transação'},
  it:{'Review before publishing':'Controlla prima di pubblicare','Check every detail before creating the public Deal Link.':'Controlla ogni dettaglio prima di creare il link pubblico della trattativa.','No media selected':'Nessun file selezionato','The Deal Link is not public until you confirm.':'Il link non sarà pubblico finché non confermi.','Confirm and publish':'Conferma e pubblica','Review deal':'Controlla trattativa'},
  ru:{'Review before publishing':'Проверьте перед публикацией','Check every detail before creating the public Deal Link.':'Проверьте все данные перед созданием публичной ссылки на сделку.','No media selected':'Медиафайлы не выбраны','The Deal Link is not public until you confirm.':'Ссылка не станет публичной до вашего подтверждения.','Confirm and publish':'Подтвердить и опубликовать','Review deal':'Проверить сделку'},
  tr:{'Review before publishing':'Yayınlamadan önce inceleyin','Check every detail before creating the public Deal Link.':'Herkese açık anlaşma bağlantısını oluşturmadan önce tüm ayrıntıları kontrol edin.','No media selected':'Medya seçilmedi','The Deal Link is not public until you confirm.':'Siz onaylayana kadar bağlantı herkese açık olmaz.','Confirm and publish':'Onayla ve yayınla','Review deal':'Anlaşmayı incele'},
  el:{'Review before publishing':'Έλεγχος πριν από τη δημοσίευση','Check every detail before creating the public Deal Link.':'Ελέγξτε κάθε λεπτομέρεια πριν δημιουργήσετε τον δημόσιο σύνδεσμο της συμφωνίας.','No media selected':'Δεν επιλέχθηκαν πολυμέσα','The Deal Link is not public until you confirm.':'Ο σύνδεσμος δεν γίνεται δημόσιος μέχρι να επιβεβαιώσετε.','Confirm and publish':'Επιβεβαίωση και δημοσίευση','Review deal':'Έλεγχος συμφωνίας'},
  zh:{'Review before publishing':'发布前检查','Check every detail before creating the public Deal Link.':'创建公开交易链接前，请检查所有详细信息。','No media selected':'未选择媒体文件','The Deal Link is not public until you confirm.':'确认之前，交易链接不会公开。','Confirm and publish':'确认并发布','Review deal':'检查交易'},
  ja:{'Review before publishing':'公開前に確認','Check every detail before creating the public Deal Link.':'公開取引リンクを作成する前に、すべての詳細を確認してください。','No media selected':'メディアが選択されていません','The Deal Link is not public until you confirm.':'確認するまで取引リンクは公開されません。','Confirm and publish':'確認して公開','Review deal':'取引を確認'},
  ko:{'Review before publishing':'게시 전 검토','Check every detail before creating the public Deal Link.':'공개 거래 링크를 만들기 전에 모든 세부정보를 확인하세요.','No media selected':'선택한 미디어 없음','The Deal Link is not public until you confirm.':'확인하기 전에는 거래 링크가 공개되지 않습니다.','Confirm and publish':'확인 및 게시','Review deal':'거래 검토'},
  ar:{'Review before publishing':'المراجعة قبل النشر','Check every detail before creating the public Deal Link.':'راجع جميع التفاصيل قبل إنشاء رابط الصفقة العام.','No media selected':'لم يتم اختيار وسائط','The Deal Link is not public until you confirm.':'لن يصبح رابط الصفقة عامًا حتى تؤكد.','Confirm and publish':'تأكيد ونشر','Review deal':'مراجعة الصفقة'},
  he:{'Review before publishing':'בדיקה לפני הפרסום','Check every detail before creating the public Deal Link.':'יש לבדוק את כל הפרטים לפני יצירת קישור העסקה הציבורי.','No media selected':'לא נבחרו קובצי מדיה','The Deal Link is not public until you confirm.':'קישור העסקה לא יהיה ציבורי עד לאישור שלך.','Confirm and publish':'אישור ופרסום','Review deal':'בדיקת העסקה'},
  hi:{'Review before publishing':'प्रकाशित करने से पहले समीक्षा करें','Check every detail before creating the public Deal Link.':'सार्वजनिक डील लिंक बनाने से पहले हर विवरण जाँचें।','No media selected':'कोई मीडिया चयनित नहीं है','The Deal Link is not public until you confirm.':'आपकी पुष्टि से पहले डील लिंक सार्वजनिक नहीं होगा।','Confirm and publish':'पुष्टि करें और प्रकाशित करें','Review deal':'डील की समीक्षा करें'}
};
Object.entries(createReviewLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const savedDraftLabels:Record<string,Record<string,string>>={
  en:{'Save as draft':'Save as draft','Private draft':'Private draft','This draft is private and only you can see it.':'This draft is private and only you can see it.','Not published':'Not published','Save changes':'Save changes','Draft saved.':'Draft saved.','Deal Link published.':'Deal Link published.','draft':'draft'},
  ka:{'Save as draft':'მონახაზად შენახვა','Private draft':'პირადი მონახაზი','This draft is private and only you can see it.':'ეს მონახაზი პირადია და მხოლოდ თქვენ ხედავთ.','Not published':'გამოქვეყნებული არ არის','Save changes':'ცვლილებების შენახვა','Draft saved.':'მონახაზი შენახულია.','Deal Link published.':'Deal Link გამოქვეყნებულია.','draft':'მონახაზი'},
  de:{'Save as draft':'Als Entwurf speichern','Private draft':'Privater Entwurf','This draft is private and only you can see it.':'Dieser Entwurf ist privat und nur für Sie sichtbar.','Not published':'Nicht veröffentlicht','Save changes':'Änderungen speichern','Draft saved.':'Entwurf gespeichert.','Deal Link published.':'Deal-Link veröffentlicht.','draft':'Entwurf'},
  es:{'Save as draft':'Guardar como borrador','Private draft':'Borrador privado','This draft is private and only you can see it.':'Este borrador es privado y solo usted puede verlo.','Not published':'Sin publicar','Save changes':'Guardar cambios','Draft saved.':'Borrador guardado.','Deal Link published.':'Enlace publicado.','draft':'borrador'},
  fr:{'Save as draft':'Enregistrer comme brouillon','Private draft':'Brouillon privé','This draft is private and only you can see it.':'Ce brouillon est privé et vous seul pouvez le voir.','Not published':'Non publié','Save changes':'Enregistrer les modifications','Draft saved.':'Brouillon enregistré.','Deal Link published.':'Lien publié.','draft':'brouillon'},
  pt:{'Save as draft':'Guardar como rascunho','Private draft':'Rascunho privado','This draft is private and only you can see it.':'Este rascunho é privado e apenas o utilizador pode vê-lo.','Not published':'Não publicado','Save changes':'Guardar alterações','Draft saved.':'Rascunho guardado.','Deal Link published.':'Link publicado.','draft':'rascunho'},
  it:{'Save as draft':'Salva come bozza','Private draft':'Bozza privata','This draft is private and only you can see it.':'Questa bozza è privata e visibile solo a te.','Not published':'Non pubblicato','Save changes':'Salva modifiche','Draft saved.':'Bozza salvata.','Deal Link published.':'Link pubblicato.','draft':'bozza'},
  ru:{'Save as draft':'Сохранить как черновик','Private draft':'Личный черновик','This draft is private and only you can see it.':'Этот черновик виден только вам.','Not published':'Не опубликовано','Save changes':'Сохранить изменения','Draft saved.':'Черновик сохранён.','Deal Link published.':'Ссылка опубликована.','draft':'черновик'},
  tr:{'Save as draft':'Taslak olarak kaydet','Private draft':'Özel taslak','This draft is private and only you can see it.':'Bu taslak özeldir ve yalnızca siz görebilirsiniz.','Not published':'Yayınlanmadı','Save changes':'Değişiklikleri kaydet','Draft saved.':'Taslak kaydedildi.','Deal Link published.':'Anlaşma bağlantısı yayınlandı.','draft':'taslak'},
  el:{'Save as draft':'Αποθήκευση ως πρόχειρο','Private draft':'Ιδιωτικό πρόχειρο','This draft is private and only you can see it.':'Αυτό το πρόχειρο είναι ιδιωτικό και το βλέπετε μόνο εσείς.','Not published':'Δεν δημοσιεύτηκε','Save changes':'Αποθήκευση αλλαγών','Draft saved.':'Το πρόχειρο αποθηκεύτηκε.','Deal Link published.':'Ο σύνδεσμος δημοσιεύτηκε.','draft':'πρόχειρο'},
  zh:{'Save as draft':'保存为草稿','Private draft':'私人草稿','This draft is private and only you can see it.':'此草稿为私人内容，仅您可见。','Not published':'未发布','Save changes':'保存更改','Draft saved.':'草稿已保存。','Deal Link published.':'交易链接已发布。','draft':'草稿'},
  ja:{'Save as draft':'下書きとして保存','Private draft':'非公開の下書き','This draft is private and only you can see it.':'この下書きは非公開で、あなただけが閲覧できます。','Not published':'未公開','Save changes':'変更を保存','Draft saved.':'下書きを保存しました。','Deal Link published.':'取引リンクを公開しました。','draft':'下書き'},
  ko:{'Save as draft':'초안으로 저장','Private draft':'비공개 초안','This draft is private and only you can see it.':'이 초안은 비공개이며 본인만 볼 수 있습니다.','Not published':'게시되지 않음','Save changes':'변경사항 저장','Draft saved.':'초안이 저장되었습니다.','Deal Link published.':'거래 링크가 게시되었습니다.','draft':'초안'},
  ar:{'Save as draft':'حفظ كمسودة','Private draft':'مسودة خاصة','This draft is private and only you can see it.':'هذه المسودة خاصة ولا يراها سواك.','Not published':'غير منشور','Save changes':'حفظ التغييرات','Draft saved.':'تم حفظ المسودة.','Deal Link published.':'تم نشر رابط الصفقة.','draft':'مسودة'},
  he:{'Save as draft':'שמירה כטיוטה','Private draft':'טיוטה פרטית','This draft is private and only you can see it.':'הטיוטה פרטית ורק לך יש גישה אליה.','Not published':'לא פורסם','Save changes':'שמירת שינויים','Draft saved.':'הטיוטה נשמרה.','Deal Link published.':'קישור העסקה פורסם.','draft':'טיוטה'},
  hi:{'Save as draft':'ड्राफ़्ट के रूप में सहेजें','Private draft':'निजी ड्राफ़्ट','This draft is private and only you can see it.':'यह ड्राफ़्ट निजी है और केवल आपको दिखाई देता है।','Not published':'प्रकाशित नहीं','Save changes':'बदलाव सहेजें','Draft saved.':'ड्राफ़्ट सहेजा गया।','Deal Link published.':'डील लिंक प्रकाशित हुआ।','draft':'ड्राफ़्ट'}
};
Object.entries(savedDraftLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const draftPrivacyLabels:Record<string,Record<string,string>>={
  en:{'This draft is not shared through a Deal Link until you publish it.':'This draft is not shared through a Deal Link until you publish it.'},
  ka:{'This draft is not shared through a Deal Link until you publish it.':'გამოქვეყნებამდე ეს მონახაზი Deal Link-ით არ გაზიარდება.'},
  de:{'This draft is not shared through a Deal Link until you publish it.':'Dieser Entwurf wird erst nach der Veröffentlichung über einen Deal-Link geteilt.'},
  es:{'This draft is not shared through a Deal Link until you publish it.':'Este borrador no se comparte mediante un enlace hasta que lo publique.'},
  fr:{'This draft is not shared through a Deal Link until you publish it.':'Ce brouillon n’est pas partagé par un lien avant sa publication.'},
  pt:{'This draft is not shared through a Deal Link until you publish it.':'Este rascunho não é partilhado por um link até ser publicado.'},
  it:{'This draft is not shared through a Deal Link until you publish it.':'Questa bozza non viene condivisa tramite un link finché non la pubblichi.'},
  ru:{'This draft is not shared through a Deal Link until you publish it.':'Черновик не будет доступен по ссылке, пока вы его не опубликуете.'},
  tr:{'This draft is not shared through a Deal Link until you publish it.':'Bu taslak siz yayınlayana kadar bir anlaşma bağlantısıyla paylaşılmaz.'},
  el:{'This draft is not shared through a Deal Link until you publish it.':'Αυτό το πρόχειρο δεν κοινοποιείται μέσω συνδέσμου μέχρι να το δημοσιεύσετε.'},
  zh:{'This draft is not shared through a Deal Link until you publish it.':'在您发布之前，此草稿不会通过交易链接共享。'},
  ja:{'This draft is not shared through a Deal Link until you publish it.':'公開するまで、この下書きは取引リンクで共有されません。'},
  ko:{'This draft is not shared through a Deal Link until you publish it.':'게시하기 전에는 이 초안이 거래 링크로 공유되지 않습니다.'},
  ar:{'This draft is not shared through a Deal Link until you publish it.':'لن تتم مشاركة هذه المسودة عبر رابط الصفقة حتى تنشرها.'},
  he:{'This draft is not shared through a Deal Link until you publish it.':'הטיוטה לא תשותף באמצעות קישור עסקה עד לפרסומה.'},
  hi:{'This draft is not shared through a Deal Link until you publish it.':'जब तक आप प्रकाशित नहीं करते, यह ड्राफ़्ट डील लिंक से साझा नहीं होगा।'}
};
Object.entries(draftPrivacyLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const reportDealLabels:Record<string,Record<string,string>>={
  en:{'Trust and safety':'Trust and safety','Report suspicious deal':'Report suspicious deal','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'Help DealSafe review possible fraud, prohibited goods, or misleading information.','Report category':'Report category','Suspected fraud':'Suspected fraud','Prohibited item':'Prohibited item','Misleading information':'Misleading information','Duplicate or stolen photos':'Duplicate or stolen photos','Other':'Other','Details':'Details','Describe what you noticed without sharing passwords or financial information.':'Describe what you noticed without sharing passwords or financial information.','Submit report':'Submit report','Sign in so the report can be recorded and protected from abuse.':'Sign in so the report can be recorded and protected from abuse.','Sign in to report':'Sign in to report','Report submitted':'Report submitted','Thank you. The report was recorded for review.':'Thank you. The report was recorded for review.'},
  ka:{'Trust and safety':'ნდობა და უსაფრთხოება','Report suspicious deal':'საეჭვო გარიგების შეტყობინება','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'დაეხმარეთ DealSafe-ს შესაძლო თაღლითობის, აკრძალული ნივთის ან მცდარი ინფორმაციის განხილვაში.','Report category':'შეტყობინების კატეგორია','Suspected fraud':'სავარაუდო თაღლითობა','Prohibited item':'აკრძალული ნივთი','Misleading information':'მცდარი ინფორმაცია','Duplicate or stolen photos':'გამეორებული ან მოპარული ფოტოები','Other':'სხვა','Details':'დეტალები','Describe what you noticed without sharing passwords or financial information.':'აღწერეთ, რა შენიშნეთ; არ მიუთითოთ პაროლები ან ფინანსური ინფორმაცია.','Submit report':'შეტყობინების გაგზავნა','Sign in so the report can be recorded and protected from abuse.':'შედით ანგარიშში, რათა შეტყობინება დაფიქსირდეს და ბოროტად გამოყენებისგან დაცული იყოს.','Sign in to report':'შესვლა და შეტყობინება','Report submitted':'შეტყობინება გაგზავნილია','Thank you. The report was recorded for review.':'გმადლობთ. შეტყობინება განხილვისთვის დაფიქსირდა.'},
  de:{'Trust and safety':'Vertrauen und Sicherheit','Report suspicious deal':'Verdächtigen Deal melden','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'Helfen Sie DealSafe, möglichen Betrug, verbotene Waren oder irreführende Angaben zu prüfen.','Report category':'Meldekategorie','Suspected fraud':'Betrugsverdacht','Prohibited item':'Verbotener Artikel','Misleading information':'Irreführende Angaben','Duplicate or stolen photos':'Doppelte oder gestohlene Fotos','Other':'Sonstiges','Details':'Details','Describe what you noticed without sharing passwords or financial information.':'Beschreiben Sie Ihre Beobachtung, ohne Passwörter oder Finanzdaten anzugeben.','Submit report':'Meldung senden','Sign in so the report can be recorded and protected from abuse.':'Melden Sie sich an, damit die Meldung erfasst und vor Missbrauch geschützt wird.','Sign in to report':'Zum Melden anmelden','Report submitted':'Meldung gesendet','Thank you. The report was recorded for review.':'Vielen Dank. Die Meldung wurde zur Prüfung erfasst.'},
  es:{'Trust and safety':'Confianza y seguridad','Report suspicious deal':'Denunciar operación sospechosa','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'Ayude a DealSafe a revisar posibles fraudes, artículos prohibidos o información engañosa.','Report category':'Categoría de denuncia','Suspected fraud':'Posible fraude','Prohibited item':'Artículo prohibido','Misleading information':'Información engañosa','Duplicate or stolen photos':'Fotos duplicadas o robadas','Other':'Otro','Details':'Detalles','Describe what you noticed without sharing passwords or financial information.':'Describa lo que observó sin compartir contraseñas ni información financiera.','Submit report':'Enviar denuncia','Sign in so the report can be recorded and protected from abuse.':'Inicie sesión para registrar la denuncia y protegerla frente a abusos.','Sign in to report':'Iniciar sesión para denunciar','Report submitted':'Denuncia enviada','Thank you. The report was recorded for review.':'Gracias. La denuncia quedó registrada para su revisión.'},
  fr:{'Trust and safety':'Confiance et sécurité','Report suspicious deal':'Signaler une transaction suspecte','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'Aidez DealSafe à examiner une fraude possible, un article interdit ou des informations trompeuses.','Report category':'Catégorie du signalement','Suspected fraud':'Fraude présumée','Prohibited item':'Article interdit','Misleading information':'Informations trompeuses','Duplicate or stolen photos':'Photos dupliquées ou volées','Other':'Autre','Details':'Détails','Describe what you noticed without sharing passwords or financial information.':'Décrivez ce que vous avez remarqué sans communiquer de mot de passe ni de données financières.','Submit report':'Envoyer le signalement','Sign in so the report can be recorded and protected from abuse.':'Connectez-vous afin que le signalement soit enregistré et protégé contre les abus.','Sign in to report':'Se connecter pour signaler','Report submitted':'Signalement envoyé','Thank you. The report was recorded for review.':'Merci. Le signalement a été enregistré pour examen.'},
  pt:{'Trust and safety':'Confiança e segurança','Report suspicious deal':'Denunciar transação suspeita','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'Ajude a DealSafe a analisar possíveis fraudes, artigos proibidos ou informações enganosas.','Report category':'Categoria da denúncia','Suspected fraud':'Suspeita de fraude','Prohibited item':'Artigo proibido','Misleading information':'Informação enganosa','Duplicate or stolen photos':'Fotos duplicadas ou roubadas','Other':'Outro','Details':'Detalhes','Describe what you noticed without sharing passwords or financial information.':'Descreva o que observou sem partilhar palavras-passe ou informações financeiras.','Submit report':'Enviar denúncia','Sign in so the report can be recorded and protected from abuse.':'Inicie sessão para que a denúncia seja registada e protegida contra abusos.','Sign in to report':'Iniciar sessão para denunciar','Report submitted':'Denúncia enviada','Thank you. The report was recorded for review.':'Obrigado. A denúncia foi registada para análise.'},
  it:{'Trust and safety':'Affidabilità e sicurezza','Report suspicious deal':'Segnala trattativa sospetta','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'Aiuta DealSafe a verificare possibili frodi, articoli vietati o informazioni fuorvianti.','Report category':'Categoria della segnalazione','Suspected fraud':'Sospetta frode','Prohibited item':'Articolo vietato','Misleading information':'Informazioni fuorvianti','Duplicate or stolen photos':'Foto duplicate o rubate','Other':'Altro','Details':'Dettagli','Describe what you noticed without sharing passwords or financial information.':'Descrivi ciò che hai notato senza condividere password o dati finanziari.','Submit report':'Invia segnalazione','Sign in so the report can be recorded and protected from abuse.':'Accedi affinché la segnalazione venga registrata e protetta dagli abusi.','Sign in to report':'Accedi per segnalare','Report submitted':'Segnalazione inviata','Thank you. The report was recorded for review.':'Grazie. La segnalazione è stata registrata per la verifica.'},
  ru:{'Trust and safety':'Доверие и безопасность','Report suspicious deal':'Сообщить о подозрительной сделке','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'Помогите DealSafe проверить возможное мошенничество, запрещённый товар или вводящую в заблуждение информацию.','Report category':'Категория жалобы','Suspected fraud':'Подозрение на мошенничество','Prohibited item':'Запрещённый товар','Misleading information':'Недостоверная информация','Duplicate or stolen photos':'Дублированные или украденные фото','Other':'Другое','Details':'Подробности','Describe what you noticed without sharing passwords or financial information.':'Опишите замеченное, не указывая пароли и финансовую информацию.','Submit report':'Отправить жалобу','Sign in so the report can be recorded and protected from abuse.':'Войдите, чтобы жалоба была зарегистрирована и защищена от злоупотреблений.','Sign in to report':'Войти и сообщить','Report submitted':'Жалоба отправлена','Thank you. The report was recorded for review.':'Спасибо. Жалоба зарегистрирована для проверки.'},
  tr:{'Trust and safety':'Güven ve emniyet','Report suspicious deal':'Şüpheli anlaşmayı bildir','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'DealSafe’in olası dolandırıcılık, yasaklı ürün veya yanıltıcı bilgileri incelemesine yardımcı olun.','Report category':'Bildirim kategorisi','Suspected fraud':'Dolandırıcılık şüphesi','Prohibited item':'Yasaklı ürün','Misleading information':'Yanıltıcı bilgi','Duplicate or stolen photos':'Kopya veya çalıntı fotoğraflar','Other':'Diğer','Details':'Ayrıntılar','Describe what you noticed without sharing passwords or financial information.':'Parola veya finansal bilgi paylaşmadan fark ettiğiniz durumu açıklayın.','Submit report':'Bildirimi gönder','Sign in so the report can be recorded and protected from abuse.':'Bildirimin kaydedilmesi ve kötüye kullanımdan korunması için giriş yapın.','Sign in to report':'Bildirmek için giriş yap','Report submitted':'Bildirim gönderildi','Thank you. The report was recorded for review.':'Teşekkürler. Bildirim inceleme için kaydedildi.'},
  el:{'Trust and safety':'Εμπιστοσύνη και ασφάλεια','Report suspicious deal':'Αναφορά ύποπτης συμφωνίας','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'Βοηθήστε το DealSafe να εξετάσει πιθανή απάτη, απαγορευμένα αγαθά ή παραπλανητικές πληροφορίες.','Report category':'Κατηγορία αναφοράς','Suspected fraud':'Ύποπτη απάτη','Prohibited item':'Απαγορευμένο αντικείμενο','Misleading information':'Παραπλανητικές πληροφορίες','Duplicate or stolen photos':'Διπλές ή κλεμμένες φωτογραφίες','Other':'Άλλο','Details':'Λεπτομέρειες','Describe what you noticed without sharing passwords or financial information.':'Περιγράψτε τι παρατηρήσατε χωρίς κωδικούς ή οικονομικά στοιχεία.','Submit report':'Υποβολή αναφοράς','Sign in so the report can be recorded and protected from abuse.':'Συνδεθείτε ώστε η αναφορά να καταγραφεί και να προστατευτεί από κατάχρηση.','Sign in to report':'Σύνδεση για αναφορά','Report submitted':'Η αναφορά υποβλήθηκε','Thank you. The report was recorded for review.':'Ευχαριστούμε. Η αναφορά καταγράφηκε για εξέταση.'},
  zh:{'Trust and safety':'信任与安全','Report suspicious deal':'举报可疑交易','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'帮助 DealSafe 审查可能的欺诈、违禁品或误导性信息。','Report category':'举报类别','Suspected fraud':'疑似欺诈','Prohibited item':'违禁物品','Misleading information':'误导性信息','Duplicate or stolen photos':'重复或盗用的照片','Other':'其他','Details':'详细信息','Describe what you noticed without sharing passwords or financial information.':'请描述您发现的问题，不要提供密码或财务信息。','Submit report':'提交举报','Sign in so the report can be recorded and protected from abuse.':'请登录，以便记录举报并防止滥用。','Sign in to report':'登录后举报','Report submitted':'举报已提交','Thank you. The report was recorded for review.':'谢谢。举报已记录，等待审查。'},
  ja:{'Trust and safety':'信頼と安全','Report suspicious deal':'不審な取引を報告','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'詐欺の可能性、禁止商品、誤解を招く情報の確認にご協力ください。','Report category':'報告カテゴリー','Suspected fraud':'詐欺の疑い','Prohibited item':'禁止商品','Misleading information':'誤解を招く情報','Duplicate or stolen photos':'重複または盗用された写真','Other':'その他','Details':'詳細','Describe what you noticed without sharing passwords or financial information.':'パスワードや金融情報を含めず、気づいた点を説明してください。','Submit report':'報告を送信','Sign in so the report can be recorded and protected from abuse.':'報告を記録し悪用を防ぐため、ログインしてください。','Sign in to report':'ログインして報告','Report submitted':'報告を送信しました','Thank you. The report was recorded for review.':'ありがとうございます。確認のため報告を記録しました。'},
  ko:{'Trust and safety':'신뢰 및 안전','Report suspicious deal':'의심스러운 거래 신고','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'DealSafe가 사기 가능성, 금지 상품 또는 오해의 소지가 있는 정보를 검토하도록 도와주세요.','Report category':'신고 유형','Suspected fraud':'사기 의심','Prohibited item':'금지 상품','Misleading information':'오해의 소지가 있는 정보','Duplicate or stolen photos':'중복 또는 도용 사진','Other':'기타','Details':'세부정보','Describe what you noticed without sharing passwords or financial information.':'비밀번호나 금융정보를 제외하고 발견한 내용을 설명하세요.','Submit report':'신고 제출','Sign in so the report can be recorded and protected from abuse.':'신고를 기록하고 악용을 방지하려면 로그인하세요.','Sign in to report':'로그인하여 신고','Report submitted':'신고가 제출되었습니다','Thank you. The report was recorded for review.':'감사합니다. 검토를 위해 신고가 기록되었습니다.'},
  ar:{'Trust and safety':'الثقة والسلامة','Report suspicious deal':'الإبلاغ عن صفقة مشبوهة','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'ساعد DealSafe في مراجعة الاحتيال المحتمل أو السلع المحظورة أو المعلومات المضللة.','Report category':'فئة البلاغ','Suspected fraud':'اشتباه في احتيال','Prohibited item':'سلعة محظورة','Misleading information':'معلومات مضللة','Duplicate or stolen photos':'صور مكررة أو مسروقة','Other':'أخرى','Details':'التفاصيل','Describe what you noticed without sharing passwords or financial information.':'صف ما لاحظته دون مشاركة كلمات المرور أو المعلومات المالية.','Submit report':'إرسال البلاغ','Sign in so the report can be recorded and protected from abuse.':'سجّل الدخول ليتم تسجيل البلاغ وحمايته من إساءة الاستخدام.','Sign in to report':'تسجيل الدخول للإبلاغ','Report submitted':'تم إرسال البلاغ','Thank you. The report was recorded for review.':'شكرًا. تم تسجيل البلاغ للمراجعة.'},
  he:{'Trust and safety':'אמון ובטיחות','Report suspicious deal':'דיווח על עסקה חשודה','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'עזרו ל-DealSafe לבדוק הונאה אפשרית, פריט אסור או מידע מטעה.','Report category':'קטגוריית הדיווח','Suspected fraud':'חשד להונאה','Prohibited item':'פריט אסור','Misleading information':'מידע מטעה','Duplicate or stolen photos':'תמונות כפולות או גנובות','Other':'אחר','Details':'פרטים','Describe what you noticed without sharing passwords or financial information.':'תארו מה הבחנתם בלי לשתף סיסמאות או מידע פיננסי.','Submit report':'שליחת דיווח','Sign in so the report can be recorded and protected from abuse.':'יש להתחבר כדי לתעד את הדיווח ולהגן עליו משימוש לרעה.','Sign in to report':'התחברות לדיווח','Report submitted':'הדיווח נשלח','Thank you. The report was recorded for review.':'תודה. הדיווח תועד לבדיקה.'},
  hi:{'Trust and safety':'विश्वास और सुरक्षा','Report suspicious deal':'संदिग्ध डील की रिपोर्ट करें','Help DealSafe review possible fraud, prohibited goods, or misleading information.':'संभावित धोखाधड़ी, प्रतिबंधित वस्तु या भ्रामक जानकारी की समीक्षा में DealSafe की मदद करें।','Report category':'रिपोर्ट श्रेणी','Suspected fraud':'संदिग्ध धोखाधड़ी','Prohibited item':'प्रतिबंधित वस्तु','Misleading information':'भ्रामक जानकारी','Duplicate or stolen photos':'डुप्लिकेट या चोरी की तस्वीरें','Other':'अन्य','Details':'विवरण','Describe what you noticed without sharing passwords or financial information.':'पासवर्ड या वित्तीय जानकारी साझा किए बिना अपनी जानकारी लिखें।','Submit report':'रिपोर्ट भेजें','Sign in so the report can be recorded and protected from abuse.':'रिपोर्ट दर्ज करने और दुरुपयोग से बचाने के लिए साइन इन करें।','Sign in to report':'रिपोर्ट के लिए साइन इन करें','Report submitted':'रिपोर्ट भेजी गई','Thank you. The report was recorded for review.':'धन्यवाद। समीक्षा के लिए रिपोर्ट दर्ज कर ली गई है।'}
};
Object.entries(reportDealLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const adminCenterLabels:Record<string,Record<string,string>>={
  en:{'Admin':'Admin','Admin review':'Admin review','Moderation queue':'Moderation queue','Review reported deals and record a decision.':'Review reported deals and record a decision.','Open reports':'Open reports','Reviewed':'Reviewed','Dismissed':'Dismissed','All reports':'All reports','Loading reports…':'Loading reports…','Open Deal Link':'Open Deal Link','Reporter':'Reporter','Resolution note':'Resolution note','Record what was checked and why this decision was made.':'Record what was checked and why this decision was made.','Dismiss report':'Dismiss report','Mark reviewed':'Mark reviewed','No reports in this queue.':'No reports in this queue.','Decision saved.':'Decision saved.','reviewed':'reviewed','dismissed':'dismissed','open':'open'},
  ka:{'Admin':'ადმინისტრატორი','Admin review':'ადმინისტრატორის განხილვა','Moderation queue':'მოდერაციის რიგი','Review reported deals and record a decision.':'განიხილეთ მონიშნული გარიგებები და დააფიქსირეთ გადაწყვეტილება.','Open reports':'ღია შეტყობინებები','Reviewed':'განხილული','Dismissed':'უარყოფილი','All reports':'ყველა შეტყობინება','Loading reports…':'შეტყობინებები იტვირთება…','Open Deal Link':'Deal Link-ის გახსნა','Reporter':'შემტყობინებელი','Resolution note':'გადაწყვეტილების შენიშვნა','Record what was checked and why this decision was made.':'ჩაწერეთ, რა გადაამოწმეთ და რატომ მიიღეთ ეს გადაწყვეტილება.','Dismiss report':'შეტყობინების უარყოფა','Mark reviewed':'განხილულად მონიშვნა','No reports in this queue.':'ამ რიგში შეტყობინებები არ არის.','Decision saved.':'გადაწყვეტილება შენახულია.','reviewed':'განხილული','dismissed':'უარყოფილი','open':'ღია'},
  de:{'Admin':'Admin','Admin review':'Admin-Prüfung','Moderation queue':'Moderationswarteschlange','Review reported deals and record a decision.':'Prüfen Sie gemeldete Deals und dokumentieren Sie die Entscheidung.','Open reports':'Offene Meldungen','Reviewed':'Geprüft','Dismissed':'Abgewiesen','All reports':'Alle Meldungen','Loading reports…':'Meldungen werden geladen…','Open Deal Link':'Deal-Link öffnen','Reporter':'Meldende Person','Resolution note':'Entscheidungsnotiz','Record what was checked and why this decision was made.':'Dokumentieren Sie die Prüfung und den Grund für die Entscheidung.','Dismiss report':'Meldung abweisen','Mark reviewed':'Als geprüft markieren','No reports in this queue.':'Keine Meldungen in dieser Warteschlange.','Decision saved.':'Entscheidung gespeichert.','reviewed':'geprüft','dismissed':'abgewiesen','open':'offen'},
  es:{'Admin':'Administración','Admin review':'Revisión administrativa','Moderation queue':'Cola de moderación','Review reported deals and record a decision.':'Revise las operaciones denunciadas y registre una decisión.','Open reports':'Denuncias abiertas','Reviewed':'Revisadas','Dismissed':'Descartadas','All reports':'Todas las denuncias','Loading reports…':'Cargando denuncias…','Open Deal Link':'Abrir enlace','Reporter':'Denunciante','Resolution note':'Nota de resolución','Record what was checked and why this decision was made.':'Registre qué se comprobó y por qué se tomó esta decisión.','Dismiss report':'Descartar denuncia','Mark reviewed':'Marcar como revisada','No reports in this queue.':'No hay denuncias en esta cola.','Decision saved.':'Decisión guardada.','reviewed':'revisada','dismissed':'descartada','open':'abierta'},
  fr:{'Admin':'Administration','Admin review':'Examen administratif','Moderation queue':'File de modération','Review reported deals and record a decision.':'Examinez les transactions signalées et consignez une décision.','Open reports':'Signalements ouverts','Reviewed':'Examinés','Dismissed':'Rejetés','All reports':'Tous les signalements','Loading reports…':'Chargement des signalements…','Open Deal Link':'Ouvrir le lien','Reporter':'Auteur du signalement','Resolution note':'Note de résolution','Record what was checked and why this decision was made.':'Consignez les vérifications et la raison de la décision.','Dismiss report':'Rejeter le signalement','Mark reviewed':'Marquer comme examiné','No reports in this queue.':'Aucun signalement dans cette file.','Decision saved.':'Décision enregistrée.','reviewed':'examiné','dismissed':'rejeté','open':'ouvert'},
  pt:{'Admin':'Administração','Admin review':'Revisão administrativa','Moderation queue':'Fila de moderação','Review reported deals and record a decision.':'Analise as transações denunciadas e registe uma decisão.','Open reports':'Denúncias abertas','Reviewed':'Analisadas','Dismissed':'Rejeitadas','All reports':'Todas as denúncias','Loading reports…':'A carregar denúncias…','Open Deal Link':'Abrir link','Reporter':'Denunciante','Resolution note':'Nota de resolução','Record what was checked and why this decision was made.':'Registe o que foi verificado e a razão da decisão.','Dismiss report':'Rejeitar denúncia','Mark reviewed':'Marcar como analisada','No reports in this queue.':'Não há denúncias nesta fila.','Decision saved.':'Decisão guardada.','reviewed':'analisada','dismissed':'rejeitada','open':'aberta'},
  it:{'Admin':'Amministrazione','Admin review':'Revisione amministrativa','Moderation queue':'Coda di moderazione','Review reported deals and record a decision.':'Esamina le trattative segnalate e registra una decisione.','Open reports':'Segnalazioni aperte','Reviewed':'Esaminate','Dismissed':'Respinte','All reports':'Tutte le segnalazioni','Loading reports…':'Caricamento segnalazioni…','Open Deal Link':'Apri link','Reporter':'Segnalante','Resolution note':'Nota di risoluzione','Record what was checked and why this decision was made.':'Registra cosa è stato verificato e il motivo della decisione.','Dismiss report':'Respingi segnalazione','Mark reviewed':'Segna come esaminata','No reports in this queue.':'Nessuna segnalazione in questa coda.','Decision saved.':'Decisione salvata.','reviewed':'esaminata','dismissed':'respinta','open':'aperta'},
  ru:{'Admin':'Администратор','Admin review':'Проверка администратора','Moderation queue':'Очередь модерации','Review reported deals and record a decision.':'Проверяйте жалобы на сделки и фиксируйте решение.','Open reports':'Открытые жалобы','Reviewed':'Проверенные','Dismissed':'Отклонённые','All reports':'Все жалобы','Loading reports…':'Загрузка жалоб…','Open Deal Link':'Открыть ссылку','Reporter':'Автор жалобы','Resolution note':'Комментарий к решению','Record what was checked and why this decision was made.':'Укажите, что было проверено и почему принято это решение.','Dismiss report':'Отклонить жалобу','Mark reviewed':'Отметить проверенной','No reports in this queue.':'В этой очереди нет жалоб.','Decision saved.':'Решение сохранено.','reviewed':'проверена','dismissed':'отклонена','open':'открыта'},
  tr:{'Admin':'Yönetici','Admin review':'Yönetici incelemesi','Moderation queue':'Denetim kuyruğu','Review reported deals and record a decision.':'Bildirilen anlaşmaları inceleyin ve kararı kaydedin.','Open reports':'Açık bildirimler','Reviewed':'İncelenen','Dismissed':'Reddedilen','All reports':'Tüm bildirimler','Loading reports…':'Bildirimler yükleniyor…','Open Deal Link':'Anlaşma bağlantısını aç','Reporter':'Bildiren','Resolution note':'Karar notu','Record what was checked and why this decision was made.':'Nelerin kontrol edildiğini ve kararın nedenini kaydedin.','Dismiss report':'Bildirimi reddet','Mark reviewed':'İncelendi olarak işaretle','No reports in this queue.':'Bu kuyrukta bildirim yok.','Decision saved.':'Karar kaydedildi.','reviewed':'incelendi','dismissed':'reddedildi','open':'açık'},
  el:{'Admin':'Διαχειριστής','Admin review':'Έλεγχος διαχειριστή','Moderation queue':'Ουρά εποπτείας','Review reported deals and record a decision.':'Εξετάστε τις αναφερόμενες συμφωνίες και καταγράψτε απόφαση.','Open reports':'Ανοιχτές αναφορές','Reviewed':'Εξετάστηκαν','Dismissed':'Απορρίφθηκαν','All reports':'Όλες οι αναφορές','Loading reports…':'Φόρτωση αναφορών…','Open Deal Link':'Άνοιγμα συνδέσμου','Reporter':'Αναφέρων','Resolution note':'Σημείωση απόφασης','Record what was checked and why this decision was made.':'Καταγράψτε τι ελέγχθηκε και γιατί λήφθηκε η απόφαση.','Dismiss report':'Απόρριψη αναφοράς','Mark reviewed':'Σήμανση ως εξετασμένη','No reports in this queue.':'Δεν υπάρχουν αναφορές σε αυτή την ουρά.','Decision saved.':'Η απόφαση αποθηκεύτηκε.','reviewed':'εξετάστηκε','dismissed':'απορρίφθηκε','open':'ανοιχτή'},
  zh:{'Admin':'管理员','Admin review':'管理员审核','Moderation queue':'审核队列','Review reported deals and record a decision.':'审核被举报的交易并记录处理决定。','Open reports':'待处理举报','Reviewed':'已审核','Dismissed':'已驳回','All reports':'全部举报','Loading reports…':'正在加载举报…','Open Deal Link':'打开交易链接','Reporter':'举报人','Resolution note':'处理说明','Record what was checked and why this decision was made.':'记录检查内容以及作出此决定的原因。','Dismiss report':'驳回举报','Mark reviewed':'标记为已审核','No reports in this queue.':'此队列中没有举报。','Decision saved.':'决定已保存。','reviewed':'已审核','dismissed':'已驳回','open':'待处理'},
  ja:{'Admin':'管理者','Admin review':'管理者レビュー','Moderation queue':'モデレーションキュー','Review reported deals and record a decision.':'報告された取引を確認し、判断を記録します。','Open reports':'未処理の報告','Reviewed':'確認済み','Dismissed':'却下済み','All reports':'すべての報告','Loading reports…':'報告を読み込み中…','Open Deal Link':'取引リンクを開く','Reporter':'報告者','Resolution note':'判断メモ','Record what was checked and why this decision was made.':'確認内容と判断理由を記録してください。','Dismiss report':'報告を却下','Mark reviewed':'確認済みにする','No reports in this queue.':'このキューに報告はありません。','Decision saved.':'判断を保存しました。','reviewed':'確認済み','dismissed':'却下済み','open':'未処理'},
  ko:{'Admin':'관리자','Admin review':'관리자 검토','Moderation queue':'검토 대기열','Review reported deals and record a decision.':'신고된 거래를 검토하고 결정을 기록하세요.','Open reports':'미처리 신고','Reviewed':'검토됨','Dismissed':'기각됨','All reports':'모든 신고','Loading reports…':'신고 불러오는 중…','Open Deal Link':'거래 링크 열기','Reporter':'신고자','Resolution note':'결정 메모','Record what was checked and why this decision was made.':'확인한 내용과 결정 이유를 기록하세요.','Dismiss report':'신고 기각','Mark reviewed':'검토 완료로 표시','No reports in this queue.':'이 대기열에 신고가 없습니다.','Decision saved.':'결정이 저장되었습니다.','reviewed':'검토됨','dismissed':'기각됨','open':'미처리'},
  ar:{'Admin':'المشرف','Admin review':'مراجعة المشرف','Moderation queue':'قائمة الإشراف','Review reported deals and record a decision.':'راجع الصفقات المبلغ عنها وسجّل القرار.','Open reports':'البلاغات المفتوحة','Reviewed':'تمت مراجعتها','Dismissed':'مرفوضة','All reports':'كل البلاغات','Loading reports…':'جارٍ تحميل البلاغات…','Open Deal Link':'فتح رابط الصفقة','Reporter':'مقدم البلاغ','Resolution note':'ملاحظة القرار','Record what was checked and why this decision was made.':'سجّل ما تم التحقق منه وسبب اتخاذ القرار.','Dismiss report':'رفض البلاغ','Mark reviewed':'وضع علامة تمت المراجعة','No reports in this queue.':'لا توجد بلاغات في هذه القائمة.','Decision saved.':'تم حفظ القرار.','reviewed':'تمت المراجعة','dismissed':'مرفوض','open':'مفتوح'},
  he:{'Admin':'מנהל','Admin review':'בדיקת מנהל','Moderation queue':'תור בדיקה','Review reported deals and record a decision.':'בדיקת עסקאות שדווחו ותיעוד החלטה.','Open reports':'דיווחים פתוחים','Reviewed':'נבדקו','Dismissed':'נדחו','All reports':'כל הדיווחים','Loading reports…':'הדיווחים נטענים…','Open Deal Link':'פתיחת קישור העסקה','Reporter':'מדווח','Resolution note':'הערת החלטה','Record what was checked and why this decision was made.':'יש לתעד מה נבדק ומדוע התקבלה ההחלטה.','Dismiss report':'דחיית דיווח','Mark reviewed':'סימון כנבדק','No reports in this queue.':'אין דיווחים בתור זה.','Decision saved.':'ההחלטה נשמרה.','reviewed':'נבדק','dismissed':'נדחה','open':'פתוח'},
  hi:{'Admin':'व्यवस्थापक','Admin review':'व्यवस्थापक समीक्षा','Moderation queue':'समीक्षा कतार','Review reported deals and record a decision.':'रिपोर्ट की गई डील की समीक्षा करें और निर्णय दर्ज करें।','Open reports':'खुली रिपोर्ट','Reviewed':'समीक्षित','Dismissed':'खारिज','All reports':'सभी रिपोर्ट','Loading reports…':'रिपोर्ट लोड हो रही हैं…','Open Deal Link':'डील लिंक खोलें','Reporter':'रिपोर्टकर्ता','Resolution note':'निर्णय टिप्पणी','Record what was checked and why this decision was made.':'क्या जाँचा गया और यह निर्णय क्यों लिया गया, दर्ज करें।','Dismiss report':'रिपोर्ट खारिज करें','Mark reviewed':'समीक्षित चिह्नित करें','No reports in this queue.':'इस कतार में कोई रिपोर्ट नहीं है।','Decision saved.':'निर्णय सहेजा गया।','reviewed':'समीक्षित','dismissed':'खारिज','open':'खुली'}
};
Object.entries(adminCenterLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const moderationActionLabels:Record<string,Record<string,string>>={
  en:{'Visible':'Visible','Hidden':'Hidden','Hide Deal Link':'Hide Deal Link','Restore Deal Link':'Restore Deal Link','Deal hidden from public access.':'Deal hidden from public access.','Deal restored to public access.':'Deal restored to public access.','Hidden Deal Links cannot be opened or accepted until restored.':'Hidden Deal Links cannot be opened or accepted until restored.'},
  ka:{'Visible':'ხილული','Hidden':'დამალული','Hide Deal Link':'Deal Link-ის დამალვა','Restore Deal Link':'Deal Link-ის აღდგენა','Deal hidden from public access.':'Deal Link საჯარო წვდომიდან დაიმალა.','Deal restored to public access.':'Deal Link საჯარო წვდომისთვის აღდგა.','Hidden Deal Links cannot be opened or accepted until restored.':'დამალული Deal Link ვერ გაიხსნება და ვერ დადასტურდება, სანამ არ აღდგება.'},
  de:{'Visible':'Sichtbar','Hidden':'Ausgeblendet','Hide Deal Link':'Deal-Link ausblenden','Restore Deal Link':'Deal-Link wiederherstellen','Deal hidden from public access.':'Der Deal-Link wurde öffentlich ausgeblendet.','Deal restored to public access.':'Der Deal-Link ist wieder öffentlich zugänglich.','Hidden Deal Links cannot be opened or accepted until restored.':'Ausgeblendete Deal-Links können bis zur Wiederherstellung nicht geöffnet oder angenommen werden.'},
  es:{'Visible':'Visible','Hidden':'Oculto','Hide Deal Link':'Ocultar Deal Link','Restore Deal Link':'Restaurar Deal Link','Deal hidden from public access.':'El Deal Link se ocultó del acceso público.','Deal restored to public access.':'El Deal Link volvió a estar disponible públicamente.','Hidden Deal Links cannot be opened or accepted until restored.':'Los Deal Links ocultos no se pueden abrir ni aceptar hasta que se restauren.'},
  fr:{'Visible':'Visible','Hidden':'Masqué','Hide Deal Link':'Masquer le Deal Link','Restore Deal Link':'Restaurer le Deal Link','Deal hidden from public access.':'Le Deal Link a été masqué au public.','Deal restored to public access.':'Le Deal Link est de nouveau accessible au public.','Hidden Deal Links cannot be opened or accepted until restored.':'Les Deal Links masqués ne peuvent être ni ouverts ni acceptés avant leur restauration.'},
  pt:{'Visible':'Visível','Hidden':'Oculto','Hide Deal Link':'Ocultar Deal Link','Restore Deal Link':'Restaurar Deal Link','Deal hidden from public access.':'O Deal Link foi ocultado do acesso público.','Deal restored to public access.':'O Deal Link voltou a estar disponível publicamente.','Hidden Deal Links cannot be opened or accepted until restored.':'Deal Links ocultos não podem ser abertos nem aceitos até serem restaurados.'},
  it:{'Visible':'Visibile','Hidden':'Nascosto','Hide Deal Link':'Nascondi Deal Link','Restore Deal Link':'Ripristina Deal Link','Deal hidden from public access.':'Il Deal Link è stato nascosto al pubblico.','Deal restored to public access.':'Il Deal Link è di nuovo accessibile al pubblico.','Hidden Deal Links cannot be opened or accepted until restored.':'I Deal Link nascosti non possono essere aperti o accettati finché non vengono ripristinati.'},
  ru:{'Visible':'Видимая','Hidden':'Скрытая','Hide Deal Link':'Скрыть Deal Link','Restore Deal Link':'Восстановить Deal Link','Deal hidden from public access.':'Deal Link скрыт из публичного доступа.','Deal restored to public access.':'Публичный доступ к Deal Link восстановлен.','Hidden Deal Links cannot be opened or accepted until restored.':'Скрытые Deal Link нельзя открыть или принять до восстановления.'},
  tr:{'Visible':'Görünür','Hidden':'Gizli','Hide Deal Link':'Deal Link’i gizle','Restore Deal Link':'Deal Link’i geri yükle','Deal hidden from public access.':'Deal Link herkese açık erişimden gizlendi.','Deal restored to public access.':'Deal Link yeniden herkese açık hale getirildi.','Hidden Deal Links cannot be opened or accepted until restored.':'Gizli Deal Link’ler geri yüklenene kadar açılamaz veya kabul edilemez.'},
  el:{'Visible':'Ορατή','Hidden':'Κρυφή','Hide Deal Link':'Απόκρυψη Deal Link','Restore Deal Link':'Επαναφορά Deal Link','Deal hidden from public access.':'Το Deal Link αποκρύφτηκε από τη δημόσια πρόσβαση.','Deal restored to public access.':'Η δημόσια πρόσβαση στο Deal Link αποκαταστάθηκε.','Hidden Deal Links cannot be opened or accepted until restored.':'Τα κρυφά Deal Links δεν μπορούν να ανοιχτούν ή να γίνουν αποδεκτά μέχρι να αποκατασταθούν.'},
  zh:{'Visible':'可见','Hidden':'已隐藏','Hide Deal Link':'隐藏交易链接','Restore Deal Link':'恢复交易链接','Deal hidden from public access.':'交易链接已从公开访问中隐藏。','Deal restored to public access.':'交易链接已恢复公开访问。','Hidden Deal Links cannot be opened or accepted until restored.':'隐藏的交易链接在恢复前无法打开或接受。'},
  ja:{'Visible':'公開','Hidden':'非表示','Hide Deal Link':'Deal Linkを非表示','Restore Deal Link':'Deal Linkを復元','Deal hidden from public access.':'Deal Linkを一般公開から非表示にしました。','Deal restored to public access.':'Deal Linkの一般公開を復元しました。','Hidden Deal Links cannot be opened or accepted until restored.':'非表示のDeal Linkは、復元されるまで開いたり承認したりできません。'},
  ko:{'Visible':'공개','Hidden':'숨김','Hide Deal Link':'Deal Link 숨기기','Restore Deal Link':'Deal Link 복원','Deal hidden from public access.':'Deal Link가 공개 접근에서 숨겨졌습니다.','Deal restored to public access.':'Deal Link의 공개 접근이 복원되었습니다.','Hidden Deal Links cannot be opened or accepted until restored.':'숨겨진 Deal Link는 복원될 때까지 열거나 수락할 수 없습니다.'},
  ar:{'Visible':'ظاهر','Hidden':'مخفي','Hide Deal Link':'إخفاء رابط الصفقة','Restore Deal Link':'استعادة رابط الصفقة','Deal hidden from public access.':'تم إخفاء رابط الصفقة عن الوصول العام.','Deal restored to public access.':'تمت استعادة الوصول العام إلى رابط الصفقة.','Hidden Deal Links cannot be opened or accepted until restored.':'لا يمكن فتح روابط الصفقات المخفية أو قبولها حتى تتم استعادتها.'},
  he:{'Visible':'גלוי','Hidden':'מוסתר','Hide Deal Link':'הסתרת קישור העסקה','Restore Deal Link':'שחזור קישור העסקה','Deal hidden from public access.':'קישור העסקה הוסתר מגישה ציבורית.','Deal restored to public access.':'הגישה הציבורית לקישור העסקה שוחזרה.','Hidden Deal Links cannot be opened or accepted until restored.':'לא ניתן לפתוח או לאשר קישורי עסקאות מוסתרים עד לשחזורם.'},
  hi:{'Visible':'दृश्यमान','Hidden':'छिपी हुई','Hide Deal Link':'डील लिंक छिपाएँ','Restore Deal Link':'डील लिंक पुनर्स्थापित करें','Deal hidden from public access.':'डील लिंक को सार्वजनिक पहुँच से छिपा दिया गया है।','Deal restored to public access.':'डील लिंक की सार्वजनिक पहुँच बहाल कर दी गई है।','Hidden Deal Links cannot be opened or accepted until restored.':'छिपे हुए डील लिंक को बहाल होने तक खोला या स्वीकार नहीं किया जा सकता।'}
};
Object.entries(moderationActionLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const applyDocumentLanguage=(language:AppLanguage)=>{document.documentElement.lang=language;document.documentElement.dir=language==='ar'||language==='he'?'rtl':'ltr'};
applyDocumentLanguage(activeLanguage);

export function getAppLanguage(){return activeLanguage}
export function setAppLanguage(language:AppLanguage){activeLanguage=language;localStorage.setItem(languageKey,language);applyDocumentLanguage(language)}
export function t(text:string){return dictionaries[activeLanguage]?.[text]||text}
