import { localePacks } from './localePacks';
import { extraLocalePacks } from './extraLocalePacks';

export const supportedLanguages=[
  {code:'en',name:'English'},
  {code:'ka',name:'ქართული'},
  {code:'de',name:'Deutsch'},
  {code:'es',name:'Español'},
  {code:'fr',name:'Français'},
  {code:'pt',name:'Português'},
  {code:'it',name:'Italiano'},
  {code:'ru',name:'Русский'},
  {code:'tr',name:'Türkçe'},
  {code:'el',name:'Ελληνικά'},
  {code:'zh',name:'简体中文'},
  {code:'ja',name:'日本語'},
  {code:'ko',name:'한국어'},
  {code:'ar',name:'العربية'},
  {code:'he',name:'עברית'},
  {code:'hi',name:'हिन्दी'}
] as const;

export type AppLanguage=typeof supportedLanguages[number]['code'];

const languageKey='dealsafe_language';
const languageCodes=new Set<string>(supportedLanguages.map(language=>language.code));
const resolveLanguage=(value:string|null):AppLanguage=>{const normalized=(value||'').toLowerCase();const exact=supportedLanguages.find(language=>language.code===normalized);if(exact)return exact.code;const base=normalized.split('-')[0];return languageCodes.has(base)?base as AppLanguage:'en'};
const storedLanguage=localStorage.getItem(languageKey);
let activeLanguage:AppLanguage=storedLanguage&&languageCodes.has(storedLanguage)?storedLanguage as AppLanguage:resolveLanguage(navigator.languages?.[0]||navigator.language);

const ka:Record<string,string>={
  'Database connected':'მონაცემთა ბაზა დაკავშირებულია','Private beta':'დახურული ბეტა','Sign in':'შესვლა','Sign out':'გასვლა',
  'Dashboard':'მთავარი გვერდი','Activity':'აქტივობა','New deal':'ახალი გარიგება','Create a Deal Link':'გარიგების ბმულის შექმნა',
  'A clearer way to make a private sale':'კერძო გაყიდვის უფრო ნათელი გზა','Put the deal in writing.':'დააფიქსირე გარიგება წერილობით.','Share it with confidence.':'გააზიარე თავდაჯერებულად.',
  'Create a single link with the item, price, parties, and agreed terms—before money or goods change hands.':'შექმენი ერთი ბმული ნივთით, ფასით, მხარეებითა და შეთანხმებული პირობებით — სანამ თანხა ან ნივთი გადაიცემა.',
  'DealSafe does not hold your money in this beta.':'ამ ბეტა ვერსიაში DealSafe თანხას არ ინახავს.','One link. The facts that matter.':'ერთი ბმული. ყველა მნიშვნელოვანი ფაქტი.',
  'Shared terms':'გაზიარებული პირობები','Price, condition, handoff, and disclosures stay together.':'ფასი, მდგომარეობა, გადაცემა და აღწერა ერთ სივრცეში რჩება.',
  'Clear verification':'ნათელი ვერიფიკაცია','See exactly which contact or identity checks are complete.':'ზუსტად ნახე, კონტაქტისა და ვინაობის რომელი შემოწმებაა დასრულებული.',
  'Recorded consent':'დაფიქსირებული თანხმობა','Both parties accept the same version of the agreement.':'ორივე მხარე შეთანხმების ერთსა და იმავე ვერსიას ადასტურებს.',
  'Your workspace':'შენი სამუშაო სივრცე','Recent deals':'ბოლო გარიგებები','Deal dashboard':'გარიგებების მართვა','Track every sale from published link to completed handoff.':'მართე ყველა გაყიდვა ბმულის გამოქვეყნებიდან ნივთის გადაცემამდე.',
  'All deals':'ყველა გარიგება','Active':'აქტიური','Completed':'დასრულებული','Total value':'სრული ღირებულება','Search by item or Deal ID':'მოძებნე ნივთით ან გარიგების ID-ით','No matching deals':'გარიგება ვერ მოიძებნა',
  'Try another search or filter, or create a new Deal Link.':'სცადე სხვა ძიება ან შექმენი ახალი გარიგების ბმული.','Create deal':'გარიგების შექმნა','Selling':'ყიდი','Buying':'ყიდულობ',
  'DealSafe account':'DealSafe ანგარიში','Create your account':'ანგარიშის შექმნა','Welcome back':'კეთილი იყოს დაბრუნება','Your name':'შენი სახელი','Email':'ელფოსტა','Password':'პაროლი','Create account':'ანგარიშის შექმნა',
  'Already have an account? Sign in':'უკვე გაქვს ანგარიში? შედი','New to DealSafe? Create account':'ახალი ხარ DealSafe-ში? შექმენი ანგარიში','Forgot password?':'დაგავიწყდა პაროლი?','Back':'უკან',
  'New Deal Link':'ახალი გარიგების ბმული','Describe what you’re selling':'აღწერე რას ყიდი','You can review every detail before the link is published.':'ბმულის გამოქვეყნებამდე ყველა დეტალს გადაამოწმებ.',
  'Item title':'ნივთის დასახელება','Price (USD)':'ფასი (USD)','Condition':'მდგომარეობა','Known condition and defects':'მდგომარეობა და ცნობილი დეფექტები','Serial or IMEI (optional)':'სერიული ნომერი ან IMEI (არასავალდებულო)','Handoff':'გადაცემის მეთოდი','Publish Deal Link':'გარიგების ბმულის გამოქვეყნება',
  'Item photos or video':'ნივთის ფოტოები ან ვიდეო','Choose photos together or add them one at a time':'აირჩიე ფოტოები ერთად ან დაამატე სათითაოდ','selected':'არჩეულია','Item details':'ნივთის დეტალები','Serial':'სერიული ნომერი','Not provided':'არ არის მითითებული',
  'Seller contact':'გამყიდველის კონტაქტი','Deal agreement':'გარიგების შეთანხმება','The buyer agrees to the stated price, condition disclosures, and handoff method.':'მყიდველი ეთანხმება მითითებულ ფასს, მდგომარეობას და გადაცემის მეთოდს.',
  'Item and defects reviewed':'ნივთი და დეფექტები გადამოწმებულია','Price confirmed':'ფასი დადასტურებულია','Handoff terms confirmed':'გადაცემის პირობები დადასტურებულია','Your full name':'შენი სრული სახელი','Buyer name':'მყიდველის სახელი','Accept these terms':'პირობების მიღება','Terms accepted':'პირობები მიღებულია','verification pending':'ვერიფიკაცია მოლოდინშია',
  'Copy Deal Link':'გარიგების ბმულის კოპირება','Ratings unlock after completion':'შეფასება გაიხსნება დასრულების შემდეგ','One rating per party, tied to this deal.':'თითო შეფასება თითოეული მხარისგან, ამ გარიგებაზე მიბმული.',
  'Agreement copy':'შეთანხმების ასლი','Save or share this record':'შეინახე ან გააზიარე ჩანაწერი','Use your browser’s print screen to save a PDF copy. The live Deal Link remains the current record.':'PDF ასლის შესანახად გამოიყენე ბეჭდვის ფუნქცია. ცოცხალი Deal Link კვლავ მთავარ ჩანაწერად რჩება.','Print / Save PDF':'PDF-ის ბეჭდვა / შენახვა','Share':'გაზიარება',
  'Show QR Code':'QR კოდის ჩვენება','Hide QR Code':'QR კოდის დამალვა','Scan to open this Deal Link on another phone.':'დაასკანერე ამ გარიგების სხვა ტელეფონში გასახსნელად.','Download QR':'QR-ის ჩამოტვირთვა','Preparing QR Code…':'QR კოდი მზადდება…',
  'Trust profile':'ნდობის პროფილი','Average rating':'საშუალო შეფასება','received':'მიღებული','Completed deals':'დასრულებული გარიგებები','Successful handoffs':'წარმატებული გადაცემები','Verification':'ვერიფიკაცია','Identity verification comes next':'შემდეგი ეტაპია ვინაობის ვერიფიკაცია','Reputation history':'რეპუტაციის ისტორია','Member since':'წევრია','No ratings yet':'შეფასებები ჯერ არ არის','Ratings received after completed deals will appear here.':'დასრულებული გარიგებების შეფასებები აქ გამოჩნდება.',
  'Account protection':'ანგარიშის დაცვა','Verification & Security Center':'ვერიფიკაციისა და უსაფრთხოების ცენტრი','Email account active':'ელფოსტა აქტიურია','Identity verification':'ვინაობის ვერიფიკაცია','Request verification':'ვერიფიკაციის მოთხოვნა','Secure handoff enabled':'უსაფრთხო გადაცემა ჩართულია',
  'Account settings':'ანგარიშის პარამეტრები','Manage your account':'ანგარიშის მართვა','Public display name':'საჯარო სახელი','This name appears on your profile and Deal Links.':'ეს სახელი გამოჩნდება პროფილსა და გარიგების ბმულებზე.','Save name':'სახელის შენახვა','Change password':'პაროლის შეცვლა','Use at least 8 characters and keep it private.':'გამოიყენე მინიმუმ 8 სიმბოლო და არავის გაუზიარო.','New password':'ახალი პაროლი','Confirm password':'გაიმეორე პაროლი','Update password':'პაროლის განახლება',
  'all':'ყველა','published':'გამოქვეყნებული','accepted':'მიღებული','completed':'დასრულებული','cancelled':'გაუქმებული','disputed':'გასაჩივრებული','not started':'არ დაწყებულა','pending':'მოლოდინშია','verified':'ვერიფიცირებული','failed':'ვერ შესრულდა',
  'Meet in person':'პირადად შეხვედრა','Ship to buyer':'მყიდველთან გაგზავნა','Like new':'თითქმის ახალი','Good':'კარგი','Fair':'დამაკმაყოფილებელი'
  ,'Creating your Deal Link…':'თქვენი გარიგების ბმული იქმნება…','Item video':'ნივთის ვიდეო','Main photo':'მთავარი ფოტო','Photo':'ფოტო',
  'Seller contact verified':'გამყიდველის კონტაქტი დადასტურებულია','Review agreement':'შეთანხმების ნახვა','At least 8 characters':'მინიმუმ 8 სიმბოლო',
  'Be specific about wear, repairs, locks, and included accessories.':'ზუსტად მიუთითე ცვეთა, შეკეთება, ბლოკირება და თანდართული აქსესუარები.','Stored privately; only last characters shown':'ინახება კონფიდენციალურად; გამოჩნდება მხოლოდ ბოლო სიმბოლოები',
  'Next in production:':'შემდეგი საწარმოო ეტაპი:','Add photos, verify contact, then preview the agreement. This prototype publishes immediately.':'დაამატე ფოტოები, დაადასტურე კონტაქტი და გადახედე შეთანხმებას. ეს პროტოტიპი ბმულს დაუყოვნებლივ აქვეყნებს.',
  'Version':'ვერსია','Buyer':'მყიდველი','Typing your name records consent for this prototype. Production language requires legal review.':'სახელის შეყვანა ამ პროტოტიპში თანხმობას აფიქსირებს. საბოლოო სამართლებრივი ტექსტი იურისტმა უნდა შეამოწმოს.',
  'No written comment.':'წერილობითი კომენტარი არ არის.','Facts, consent, and a clearer handoff.':'ფაქტები, თანხმობა და უფრო ნათელი გადაცემა.'
};

const dictionaries:Record<string,Record<string,string>>=Object.fromEntries(Object.entries(localePacks).map(([code,pack])=>[code,{...pack,...extraLocalePacks[code]}]));
dictionaries.ka={...ka,...extraLocalePacks.ka};
const financeLabels:Record<string,Record<string,string>>={
  en:{Price:'Price',Currency:'Currency'},ka:{Price:'ფასი',Currency:'ვალუტა'},de:{Price:'Preis',Currency:'Währung'},es:{Price:'Precio',Currency:'Moneda'},fr:{Price:'Prix',Currency:'Devise'},pt:{Price:'Preço',Currency:'Moeda'},it:{Price:'Prezzo',Currency:'Valuta'},ru:{Price:'Цена',Currency:'Валюта'},tr:{Price:'Fiyat',Currency:'Para birimi'},el:{Price:'Τιμή',Currency:'Νόμισμα'},zh:{Price:'价格',Currency:'货币'},ja:{Price:'価格',Currency:'通貨'},ko:{Price:'가격',Currency:'통화'},ar:{Price:'السعر',Currency:'العملة'},he:{Price:'מחיר',Currency:'מטבע'},hi:{Price:'कीमत',Currency:'मुद्रा'}
};
Object.entries(financeLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const riskLabels:Record<string,Record<string,string>>={
  en:{'Deal safety check':'Deal safety check','Risk score':'Risk score','Low concern':'Low concern','Review recommended':'Review recommended','Caution':'Caution','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.'},
  ka:{'Deal safety check':'გარიგების უსაფრთხოების შემოწმება','Risk score':'რისკის ქულა','Low concern':'დაბალი რისკი','Review recommended':'რეკომენდებულია გადამოწმება','Caution':'სიფრთხილე','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'ეს ავტომატური შემოწმება იყენებს მხოლოდ DealSafe-ის ჩანაწერში არსებულ მონაცემებს. ის არ არის ბრალდება, გარანტია ან საბაზრო ფასის შეფასება.'},
  de:{'Deal safety check':'Sicherheitsprüfung des Deals','Risk score':'Risikowert','Low concern':'Geringe Bedenken','Review recommended':'Prüfung empfohlen','Caution':'Vorsicht','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Diese automatische Prüfung verwendet nur die Angaben in diesem DealSafe-Eintrag. Sie ist keine Anschuldigung, Garantie oder Marktpreisprüfung.'},
  es:{'Deal safety check':'Comprobación de seguridad','Risk score':'Puntuación de riesgo','Low concern':'Riesgo bajo','Review recommended':'Revisión recomendada','Caution':'Precaución','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Esta comprobación automática solo usa los datos de este registro de DealSafe. No es una acusación, garantía ni comprobación del precio de mercado.'},
  fr:{'Deal safety check':'Contrôle de sécurité','Risk score':'Score de risque','Low concern':'Risque faible','Review recommended':'Vérification recommandée','Caution':'Prudence','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Ce contrôle automatique utilise uniquement les informations de cet enregistrement DealSafe. Il ne constitue ni une accusation, ni une garantie, ni une estimation du prix du marché.'},
  pt:{'Deal safety check':'Verificação de segurança','Risk score':'Pontuação de risco','Low concern':'Risco baixo','Review recommended':'Revisão recomendada','Caution':'Cuidado','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Esta verificação automática utiliza apenas os dados deste registo DealSafe. Não é uma acusação, garantia ou verificação do preço de mercado.'},
  it:{'Deal safety check':'Controllo di sicurezza','Risk score':'Punteggio di rischio','Low concern':'Rischio basso','Review recommended':'Verifica consigliata','Caution':'Attenzione','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Questo controllo automatico usa solo i dati presenti in questo record DealSafe. Non è un’accusa, una garanzia o una verifica del prezzo di mercato.'},
  ru:{'Deal safety check':'Проверка безопасности сделки','Risk score':'Оценка риска','Low concern':'Низкий риск','Review recommended':'Рекомендуется проверка','Caution':'Осторожно','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Автоматическая проверка использует только данные этой записи DealSafe. Это не обвинение, не гарантия и не проверка рыночной цены.'},
  tr:{'Deal safety check':'Anlaşma güvenlik kontrolü','Risk score':'Risk puanı','Low concern':'Düşük risk','Review recommended':'İnceleme önerilir','Caution':'Dikkat','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Bu otomatik kontrol yalnızca bu DealSafe kaydındaki bilgileri kullanır. Bir suçlama, garanti veya piyasa fiyatı kontrolü değildir.'},
  el:{'Deal safety check':'Έλεγχος ασφάλειας συμφωνίας','Risk score':'Βαθμολογία κινδύνου','Low concern':'Χαμηλός κίνδυνος','Review recommended':'Συνιστάται έλεγχος','Caution':'Προσοχή','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'Αυτός ο αυτόματος έλεγχος χρησιμοποιεί μόνο τα στοιχεία αυτής της εγγραφής DealSafe. Δεν αποτελεί κατηγορία, εγγύηση ή έλεγχο τιμής αγοράς.'},
  zh:{'Deal safety check':'交易安全检查','Risk score':'风险评分','Low concern':'低风险','Review recommended':'建议核查','Caution':'请谨慎','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'此自动检查仅使用该 DealSafe 记录中的信息，不构成指控、保证或市场价格评估。'},
  ja:{'Deal safety check':'取引の安全チェック','Risk score':'リスクスコア','Low concern':'低リスク','Review recommended':'確認を推奨','Caution':'注意','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'この自動チェックは、このDealSafe記録の情報のみを使用します。告発、保証、市場価格の確認ではありません。'},
  ko:{'Deal safety check':'거래 안전 확인','Risk score':'위험 점수','Low concern':'낮은 위험','Review recommended':'검토 권장','Caution':'주의','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'이 자동 확인은 해당 DealSafe 기록의 정보만 사용합니다. 사기 단정, 보증 또는 시세 확인이 아닙니다.'},
  ar:{'Deal safety check':'فحص سلامة الصفقة','Risk score':'درجة المخاطر','Low concern':'مخاطر منخفضة','Review recommended':'توصى بالمراجعة','Caution':'تنبيه','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'يستخدم هذا الفحص التلقائي تفاصيل سجل DealSafe هذا فقط. وهو ليس اتهامًا أو ضمانًا أو فحصًا لسعر السوق.'},
  he:{'Deal safety check':'בדיקת בטיחות העסקה','Risk score':'ציון סיכון','Low concern':'סיכון נמוך','Review recommended':'מומלץ לבדוק','Caution':'זהירות','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'הבדיקה האוטומטית משתמשת רק בפרטי רשומת DealSafe זו. היא אינה האשמה, הבטחה או בדיקת מחיר שוק.'},
  hi:{'Deal safety check':'डील सुरक्षा जाँच','Risk score':'जोखिम स्कोर','Low concern':'कम जोखिम','Review recommended':'समीक्षा की सलाह','Caution':'सावधानी','This automated check uses only the details in this DealSafe record. It is not an accusation, guarantee, or market-price check.':'यह स्वचालित जाँच केवल इस DealSafe रिकॉर्ड की जानकारी का उपयोग करती है। यह आरोप, गारंटी या बाज़ार मूल्य की जाँच नहीं है।'}
};
Object.entries(riskLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const fingerprintLabels:Record<string,Record<string,string>>={
  en:{'Agreement fingerprint':'Agreement fingerprint','Copy fingerprint':'Copy fingerprint','Fingerprint copied.':'Fingerprint copied.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.'},
  ka:{'Agreement fingerprint':'შეთანხმების ციფრული ანაბეჭდი','Copy fingerprint':'ანაბეჭდის კოპირება','Fingerprint copied.':'ანაბეჭდი დაკოპირდა.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'ეს კოდი იცვლება შეთანხმების დეტალების შეცვლისას. ის ასლების შედარებაში გეხმარებათ, მაგრამ კვალიფიციური ელექტრონული ხელმოწერა არ არის.'},
  de:{'Agreement fingerprint':'Digitaler Fingerabdruck der Vereinbarung','Copy fingerprint':'Fingerabdruck kopieren','Fingerprint copied.':'Fingerabdruck kopiert.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Dieser Code ändert sich, wenn sich die Vereinbarung ändert. Er hilft beim Vergleich von Kopien, ist aber keine qualifizierte elektronische Signatur.'},
  es:{'Agreement fingerprint':'Huella digital del acuerdo','Copy fingerprint':'Copiar huella digital','Fingerprint copied.':'Huella digital copiada.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Este código cambia cuando cambian los datos del acuerdo. Ayuda a comparar copias, pero no es una firma electrónica cualificada.'},
  fr:{'Agreement fingerprint':'Empreinte numérique de l’accord','Copy fingerprint':'Copier l’empreinte','Fingerprint copied.':'Empreinte copiée.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Ce code change lorsque les détails de l’accord changent. Il aide à comparer les copies, mais ne constitue pas une signature électronique qualifiée.'},
  pt:{'Agreement fingerprint':'Impressão digital do acordo','Copy fingerprint':'Copiar impressão digital','Fingerprint copied.':'Impressão digital copiada.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Este código muda quando os dados do acordo mudam. Ajuda a comparar cópias, mas não é uma assinatura eletrónica qualificada.'},
  it:{'Agreement fingerprint':'Impronta digitale dell’accordo','Copy fingerprint':'Copia impronta','Fingerprint copied.':'Impronta copiata.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Questo codice cambia quando cambiano i dettagli dell’accordo. Aiuta a confrontare le copie, ma non è una firma elettronica qualificata.'},
  ru:{'Agreement fingerprint':'Цифровой отпечаток соглашения','Copy fingerprint':'Копировать отпечаток','Fingerprint copied.':'Отпечаток скопирован.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Код меняется при изменении условий соглашения. Он помогает сравнивать копии, но не является квалифицированной электронной подписью.'},
  tr:{'Agreement fingerprint':'Anlaşmanın dijital parmak izi','Copy fingerprint':'Parmak izini kopyala','Fingerprint copied.':'Parmak izi kopyalandı.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Anlaşma ayrıntıları değiştiğinde bu kod da değişir. Kopyaları karşılaştırmaya yardımcı olur ancak nitelikli elektronik imza değildir.'},
  el:{'Agreement fingerprint':'Ψηφιακό αποτύπωμα συμφωνίας','Copy fingerprint':'Αντιγραφή αποτυπώματος','Fingerprint copied.':'Το αποτύπωμα αντιγράφηκε.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'Αυτός ο κωδικός αλλάζει όταν αλλάζουν οι λεπτομέρειες της συμφωνίας. Βοηθά στη σύγκριση αντιγράφων, αλλά δεν είναι εγκεκριμένη ηλεκτρονική υπογραφή.'},
  zh:{'Agreement fingerprint':'协议数字指纹','Copy fingerprint':'复制数字指纹','Fingerprint copied.':'数字指纹已复制。','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'协议详情发生变化时，此代码也会变化。它可用于比较副本，但不是合格的电子签名。'},
  ja:{'Agreement fingerprint':'契約のデジタル指紋','Copy fingerprint':'指紋をコピー','Fingerprint copied.':'指紋をコピーしました。','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'契約内容が変更されると、このコードも変わります。コピーの比較には役立ちますが、適格電子署名ではありません。'},
  ko:{'Agreement fingerprint':'계약 디지털 지문','Copy fingerprint':'지문 복사','Fingerprint copied.':'지문을 복사했습니다.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'계약 내용이 변경되면 이 코드도 변경됩니다. 사본 비교에 도움이 되지만 공인 전자서명은 아닙니다.'},
  ar:{'Agreement fingerprint':'البصمة الرقمية للاتفاقية','Copy fingerprint':'نسخ البصمة','Fingerprint copied.':'تم نسخ البصمة.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'يتغير هذا الرمز عند تغيير تفاصيل الاتفاقية. يساعد في مقارنة النسخ، لكنه ليس توقيعًا إلكترونيًا مؤهلًا.'},
  he:{'Agreement fingerprint':'טביעת האצבע הדיגיטלית של ההסכם','Copy fingerprint':'העתקת טביעת האצבע','Fingerprint copied.':'טביעת האצבע הועתקה.','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'הקוד משתנה כאשר פרטי ההסכם משתנים. הוא מסייע להשוות עותקים, אך אינו חתימה אלקטרונית מאושרת.'},
  hi:{'Agreement fingerprint':'समझौते का डिजिटल फ़िंगरप्रिंट','Copy fingerprint':'फ़िंगरप्रिंट कॉपी करें','Fingerprint copied.':'फ़िंगरप्रिंट कॉपी हो गया।','This code changes when agreement details change. It helps compare copies but is not a qualified electronic signature.':'समझौते का विवरण बदलने पर यह कोड बदल जाता है। यह प्रतियों की तुलना में मदद करता है, लेकिन मान्य इलेक्ट्रॉनिक हस्ताक्षर नहीं है।'}
};
Object.entries(fingerprintLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const inviteLabels:Record<string,Record<string,string>>={
  en:{'Invite buyer':'Invite buyer','Share this secure Deal Link with the buyer.':'Share this secure Deal Link with the buyer.','Waiting for buyer':'Waiting for buyer','The buyer must review and accept this agreement from their own account.':'The buyer must review and accept this agreement from their own account.'},
  ka:{'Invite buyer':'მყიდველის მოწვევა','Share this secure Deal Link with the buyer.':'გაუზიარეთ ეს უსაფრთხო Deal Link მყიდველს.','Waiting for buyer':'მყიდველის მოლოდინი','The buyer must review and accept this agreement from their own account.':'მყიდველმა ეს შეთანხმება საკუთარი ანგარიშიდან უნდა განიხილოს და მიიღოს.'},
  de:{'Invite buyer':'Käufer einladen','Share this secure Deal Link with the buyer.':'Diesen sicheren Deal-Link mit dem Käufer teilen.','Waiting for buyer':'Warten auf den Käufer','The buyer must review and accept this agreement from their own account.':'Der Käufer muss diese Vereinbarung in seinem eigenen Konto prüfen und akzeptieren.'},
  es:{'Invite buyer':'Invitar al comprador','Share this secure Deal Link with the buyer.':'Comparte este enlace seguro con el comprador.','Waiting for buyer':'Esperando al comprador','The buyer must review and accept this agreement from their own account.':'El comprador debe revisar y aceptar este acuerdo desde su propia cuenta.'},
  fr:{'Invite buyer':'Inviter l’acheteur','Share this secure Deal Link with the buyer.':'Partagez ce lien sécurisé avec l’acheteur.','Waiting for buyer':'En attente de l’acheteur','The buyer must review and accept this agreement from their own account.':'L’acheteur doit consulter et accepter cet accord depuis son propre compte.'},
  pt:{'Invite buyer':'Convidar o comprador','Share this secure Deal Link with the buyer.':'Partilhe este link seguro com o comprador.','Waiting for buyer':'À espera do comprador','The buyer must review and accept this agreement from their own account.':'O comprador deve rever e aceitar este acordo na sua própria conta.'},
  it:{'Invite buyer':'Invita l’acquirente','Share this secure Deal Link with the buyer.':'Condividi questo link sicuro con l’acquirente.','Waiting for buyer':'In attesa dell’acquirente','The buyer must review and accept this agreement from their own account.':'L’acquirente deve controllare e accettare l’accordo dal proprio account.'},
  ru:{'Invite buyer':'Пригласить покупателя','Share this secure Deal Link with the buyer.':'Отправьте покупателю эту безопасную ссылку на сделку.','Waiting for buyer':'Ожидание покупателя','The buyer must review and accept this agreement from their own account.':'Покупатель должен проверить и принять соглашение из своей учётной записи.'},
  tr:{'Invite buyer':'Alıcıyı davet et','Share this secure Deal Link with the buyer.':'Bu güvenli anlaşma bağlantısını alıcıyla paylaşın.','Waiting for buyer':'Alıcı bekleniyor','The buyer must review and accept this agreement from their own account.':'Alıcı bu anlaşmayı kendi hesabından inceleyip kabul etmelidir.'},
  el:{'Invite buyer':'Πρόσκληση αγοραστή','Share this secure Deal Link with the buyer.':'Μοιραστείτε αυτόν τον ασφαλή σύνδεσμο με τον αγοραστή.','Waiting for buyer':'Αναμονή αγοραστή','The buyer must review and accept this agreement from their own account.':'Ο αγοραστής πρέπει να ελέγξει και να αποδεχτεί τη συμφωνία από τον δικό του λογαριασμό.'},
  zh:{'Invite buyer':'邀请买家','Share this secure Deal Link with the buyer.':'将此安全交易链接分享给买家。','Waiting for buyer':'等待买家','The buyer must review and accept this agreement from their own account.':'买家必须使用自己的账户查看并接受此协议。'},
  ja:{'Invite buyer':'購入者を招待','Share this secure Deal Link with the buyer.':'この安全な取引リンクを購入者と共有してください。','Waiting for buyer':'購入者の確認待ち','The buyer must review and accept this agreement from their own account.':'購入者は自分のアカウントで契約を確認し、同意する必要があります。'},
  ko:{'Invite buyer':'구매자 초대','Share this secure Deal Link with the buyer.':'이 안전한 거래 링크를 구매자와 공유하세요.','Waiting for buyer':'구매자 대기 중','The buyer must review and accept this agreement from their own account.':'구매자는 자신의 계정에서 계약을 검토하고 동의해야 합니다.'},
  ar:{'Invite buyer':'دعوة المشتري','Share this secure Deal Link with the buyer.':'شارك رابط الصفقة الآمن هذا مع المشتري.','Waiting for buyer':'في انتظار المشتري','The buyer must review and accept this agreement from their own account.':'يجب على المشتري مراجعة هذه الاتفاقية وقبولها من حسابه الخاص.'},
  he:{'Invite buyer':'הזמנת הקונה','Share this secure Deal Link with the buyer.':'יש לשתף את קישור העסקה המאובטח עם הקונה.','Waiting for buyer':'ממתינים לקונה','The buyer must review and accept this agreement from their own account.':'הקונה חייב לבדוק ולאשר את ההסכם מהחשבון שלו.'},
  hi:{'Invite buyer':'खरीदार को आमंत्रित करें','Share this secure Deal Link with the buyer.':'यह सुरक्षित डील लिंक खरीदार के साथ साझा करें।','Waiting for buyer':'खरीदार की प्रतीक्षा','The buyer must review and accept this agreement from their own account.':'खरीदार को अपने खाते से इस समझौते की समीक्षा करके इसे स्वीकार करना होगा।'}
};
Object.entries(inviteLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const shareChannelLabels:Record<string,Record<string,string>>={
  en:{'More apps':'More apps','Message copied. Paste it into SMS if needed.':'Message copied. Paste it into SMS if needed.','Sharing is not available. Message copied.':'Sharing is not available. Message copied.'},
  ka:{'More apps':'სხვა აპები','Message copied. Paste it into SMS if needed.':'შეტყობინება დაკოპირდა. საჭიროების შემთხვევაში ჩასვით SMS-ში.','Sharing is not available. Message copied.':'გაზიარება მიუწვდომელია. შეტყობინება დაკოპირდა.'},
  de:{'More apps':'Weitere Apps','Message copied. Paste it into SMS if needed.':'Nachricht kopiert. Bei Bedarf in die SMS einfügen.','Sharing is not available. Message copied.':'Teilen ist nicht verfügbar. Die Nachricht wurde kopiert.'},
  es:{'More apps':'Más aplicaciones','Message copied. Paste it into SMS if needed.':'Mensaje copiado. Pégalo en el SMS si es necesario.','Sharing is not available. Message copied.':'La opción de compartir no está disponible. Se copió el mensaje.'},
  fr:{'More apps':'Plus d’applications','Message copied. Paste it into SMS if needed.':'Message copié. Collez-le dans le SMS si nécessaire.','Sharing is not available. Message copied.':'Le partage n’est pas disponible. Le message a été copié.'},
  pt:{'More apps':'Mais aplicações','Message copied. Paste it into SMS if needed.':'Mensagem copiada. Cole-a no SMS, se necessário.','Sharing is not available. Message copied.':'A partilha não está disponível. A mensagem foi copiada.'},
  it:{'More apps':'Altre app','Message copied. Paste it into SMS if needed.':'Messaggio copiato. Incollalo nell’SMS se necessario.','Sharing is not available. Message copied.':'La condivisione non è disponibile. Il messaggio è stato copiato.'},
  ru:{'More apps':'Другие приложения','Message copied. Paste it into SMS if needed.':'Сообщение скопировано. При необходимости вставьте его в SMS.','Sharing is not available. Message copied.':'Функция отправки недоступна. Сообщение скопировано.'},
  tr:{'More apps':'Diğer uygulamalar','Message copied. Paste it into SMS if needed.':'Mesaj kopyalandı. Gerekirse SMS’e yapıştırın.','Sharing is not available. Message copied.':'Paylaşım kullanılamıyor. Mesaj kopyalandı.'},
  el:{'More apps':'Περισσότερες εφαρμογές','Message copied. Paste it into SMS if needed.':'Το μήνυμα αντιγράφηκε. Επικολλήστε το στο SMS αν χρειάζεται.','Sharing is not available. Message copied.':'Η κοινή χρήση δεν είναι διαθέσιμη. Το μήνυμα αντιγράφηκε.'},
  zh:{'More apps':'更多应用','Message copied. Paste it into SMS if needed.':'消息已复制。如有需要，请粘贴到短信中。','Sharing is not available. Message copied.':'无法使用系统分享。消息已复制。'},
  ja:{'More apps':'その他のアプリ','Message copied. Paste it into SMS if needed.':'メッセージをコピーしました。必要に応じてSMSに貼り付けてください。','Sharing is not available. Message copied.':'共有を利用できません。メッセージをコピーしました。'},
  ko:{'More apps':'다른 앱','Message copied. Paste it into SMS if needed.':'메시지를 복사했습니다. 필요한 경우 SMS에 붙여넣으세요.','Sharing is not available. Message copied.':'공유 기능을 사용할 수 없습니다. 메시지를 복사했습니다.'},
  ar:{'More apps':'تطبيقات أخرى','Message copied. Paste it into SMS if needed.':'تم نسخ الرسالة. ألصقها في الرسالة النصية عند الحاجة.','Sharing is not available. Message copied.':'المشاركة غير متاحة. تم نسخ الرسالة.'},
  he:{'More apps':'אפליקציות נוספות','Message copied. Paste it into SMS if needed.':'ההודעה הועתקה. אפשר להדביק אותה ב-SMS במידת הצורך.','Sharing is not available. Message copied.':'השיתוף אינו זמין. ההודעה הועתקה.'},
  hi:{'More apps':'अन्य ऐप','Message copied. Paste it into SMS if needed.':'संदेश कॉपी हो गया। आवश्यकता होने पर इसे SMS में पेस्ट करें।','Sharing is not available. Message copied.':'शेयर करने की सुविधा उपलब्ध नहीं है। संदेश कॉपी हो गया।'}
};
Object.entries(shareChannelLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const expiryLabels:Record<string,Record<string,string>>={
  en:{'Offer valid for':'Offer valid for','1 day':'1 day','3 days':'3 days','7 days':'7 days','14 days':'14 days','30 days':'30 days','Offer active':'Offer active','Offer expires':'Offer expires','Expired':'Expired','expired':'expired','Deal Link expired':'Deal Link expired','This Deal Link can no longer be accepted.':'This Deal Link can no longer be accepted.','Buyer must accept before this time.':'Buyer must accept before this time.','This Deal Link has expired':'This Deal Link has expired'},
  ka:{'Offer valid for':'შეთავაზების მოქმედების ვადა','1 day':'1 დღე','3 days':'3 დღე','7 days':'7 დღე','14 days':'14 დღე','30 days':'30 დღე','Offer active':'შეთავაზება მოქმედია','Offer expires':'შეთავაზება იწურება','Expired':'ვადა გასულია','expired':'ვადა გასულია','Deal Link expired':'გარიგების ბმულის ვადა გავიდა','This Deal Link can no longer be accepted.':'ამ გარიგების ბმულის მიღება აღარ შეიძლება.','Buyer must accept before this time.':'მყიდველმა ამ დრომდე უნდა მიიღოს პირობები.','This Deal Link has expired':'ამ გარიგების ბმულის ვადა გავიდა'},
  de:{'Offer valid for':'Angebot gültig für','1 day':'1 Tag','3 days':'3 Tage','7 days':'7 Tage','14 days':'14 Tage','30 days':'30 Tage','Offer active':'Angebot aktiv','Offer expires':'Angebot läuft ab','Expired':'Abgelaufen','expired':'abgelaufen','Deal Link expired':'Deal-Link abgelaufen','This Deal Link can no longer be accepted.':'Dieser Deal-Link kann nicht mehr angenommen werden.','Buyer must accept before this time.':'Der Käufer muss vor diesem Zeitpunkt zustimmen.','This Deal Link has expired':'Dieser Deal-Link ist abgelaufen'},
  es:{'Offer valid for':'Oferta válida durante','1 day':'1 día','3 days':'3 días','7 days':'7 días','14 days':'14 días','30 days':'30 días','Offer active':'Oferta activa','Offer expires':'La oferta vence','Expired':'Vencida','expired':'vencida','Deal Link expired':'Enlace de la oferta vencido','This Deal Link can no longer be accepted.':'Este enlace ya no se puede aceptar.','Buyer must accept before this time.':'El comprador debe aceptar antes de esta fecha.','This Deal Link has expired':'Este enlace ha vencido'},
  fr:{'Offer valid for':'Offre valable pendant','1 day':'1 jour','3 days':'3 jours','7 days':'7 jours','14 days':'14 jours','30 days':'30 jours','Offer active':'Offre active','Offer expires':'L’offre expire','Expired':'Expirée','expired':'expirée','Deal Link expired':'Lien de l’offre expiré','This Deal Link can no longer be accepted.':'Ce lien ne peut plus être accepté.','Buyer must accept before this time.':'L’acheteur doit accepter avant cette date.','This Deal Link has expired':'Ce lien a expiré'},
  pt:{'Offer valid for':'Oferta válida por','1 day':'1 dia','3 days':'3 dias','7 days':'7 dias','14 days':'14 dias','30 days':'30 dias','Offer active':'Oferta ativa','Offer expires':'A oferta termina','Expired':'Expirada','expired':'expirada','Deal Link expired':'Link da oferta expirado','This Deal Link can no longer be accepted.':'Este link já não pode ser aceite.','Buyer must accept before this time.':'O comprador deve aceitar antes desta data.','This Deal Link has expired':'Este link expirou'},
  it:{'Offer valid for':'Offerta valida per','1 day':'1 giorno','3 days':'3 giorni','7 days':'7 giorni','14 days':'14 giorni','30 days':'30 giorni','Offer active':'Offerta attiva','Offer expires':'L’offerta scade','Expired':'Scaduta','expired':'scaduta','Deal Link expired':'Link dell’offerta scaduto','This Deal Link can no longer be accepted.':'Questo link non può più essere accettato.','Buyer must accept before this time.':'L’acquirente deve accettare prima di questa data.','This Deal Link has expired':'Questo link è scaduto'},
  ru:{'Offer valid for':'Срок действия предложения','1 day':'1 день','3 days':'3 дня','7 days':'7 дней','14 days':'14 дней','30 days':'30 дней','Offer active':'Предложение активно','Offer expires':'Предложение истекает','Expired':'Срок истёк','expired':'срок истёк','Deal Link expired':'Срок ссылки истёк','This Deal Link can no longer be accepted.':'Эту ссылку на сделку больше нельзя принять.','Buyer must accept before this time.':'Покупатель должен принять условия до этого времени.','This Deal Link has expired':'Срок действия этой ссылки истёк'},
  tr:{'Offer valid for':'Teklif geçerlilik süresi','1 day':'1 gün','3 days':'3 gün','7 days':'7 gün','14 days':'14 gün','30 days':'30 gün','Offer active':'Teklif aktif','Offer expires':'Teklifin bitişi','Expired':'Süresi doldu','expired':'süresi doldu','Deal Link expired':'Anlaşma bağlantısının süresi doldu','This Deal Link can no longer be accepted.':'Bu anlaşma bağlantısı artık kabul edilemez.','Buyer must accept before this time.':'Alıcı bu zamandan önce kabul etmelidir.','This Deal Link has expired':'Bu anlaşma bağlantısının süresi doldu'},
  el:{'Offer valid for':'Ισχύς προσφοράς','1 day':'1 ημέρα','3 days':'3 ημέρες','7 days':'7 ημέρες','14 days':'14 ημέρες','30 days':'30 ημέρες','Offer active':'Ενεργή προσφορά','Offer expires':'Η προσφορά λήγει','Expired':'Έληξε','expired':'έληξε','Deal Link expired':'Ο σύνδεσμος έληξε','This Deal Link can no longer be accepted.':'Αυτός ο σύνδεσμος δεν μπορεί πλέον να γίνει αποδεκτός.','Buyer must accept before this time.':'Ο αγοραστής πρέπει να αποδεχτεί πριν από αυτή την ώρα.','This Deal Link has expired':'Αυτός ο σύνδεσμος έχει λήξει'},
  zh:{'Offer valid for':'报价有效期','1 day':'1天','3 days':'3天','7 days':'7天','14 days':'14天','30 days':'30天','Offer active':'报价有效','Offer expires':'报价到期时间','Expired':'已过期','expired':'已过期','Deal Link expired':'交易链接已过期','This Deal Link can no longer be accepted.':'此交易链接已无法接受。','Buyer must accept before this time.':'买家必须在此时间之前接受。','This Deal Link has expired':'此交易链接已过期'},
  ja:{'Offer valid for':'オファーの有効期間','1 day':'1日','3 days':'3日','7 days':'7日','14 days':'14日','30 days':'30日','Offer active':'オファーは有効です','Offer expires':'有効期限','Expired':'期限切れ','expired':'期限切れ','Deal Link expired':'取引リンクは期限切れです','This Deal Link can no longer be accepted.':'この取引リンクはもう承認できません。','Buyer must accept before this time.':'購入者はこの時刻までに承認する必要があります。','This Deal Link has expired':'この取引リンクは期限切れです'},
  ko:{'Offer valid for':'제안 유효 기간','1 day':'1일','3 days':'3일','7 days':'7일','14 days':'14일','30 days':'30일','Offer active':'제안 활성','Offer expires':'제안 만료','Expired':'만료됨','expired':'만료됨','Deal Link expired':'거래 링크 만료','This Deal Link can no longer be accepted.':'이 거래 링크는 더 이상 수락할 수 없습니다.','Buyer must accept before this time.':'구매자는 이 시간 전에 수락해야 합니다.','This Deal Link has expired':'이 거래 링크가 만료되었습니다'},
  ar:{'Offer valid for':'مدة صلاحية العرض','1 day':'يوم واحد','3 days':'3 أيام','7 days':'7 أيام','14 days':'14 يومًا','30 days':'30 يومًا','Offer active':'العرض ساري','Offer expires':'ينتهي العرض','Expired':'منتهي','expired':'منتهي','Deal Link expired':'انتهت صلاحية رابط الصفقة','This Deal Link can no longer be accepted.':'لم يعد من الممكن قبول رابط الصفقة هذا.','Buyer must accept before this time.':'يجب على المشتري القبول قبل هذا الوقت.','This Deal Link has expired':'انتهت صلاحية رابط الصفقة هذا'},
  he:{'Offer valid for':'תוקף ההצעה','1 day':'יום אחד','3 days':'3 ימים','7 days':'7 ימים','14 days':'14 ימים','30 days':'30 ימים','Offer active':'ההצעה פעילה','Offer expires':'ההצעה תפוג','Expired':'פג תוקף','expired':'פג תוקף','Deal Link expired':'פג תוקף קישור העסקה','This Deal Link can no longer be accepted.':'לא ניתן עוד לאשר את קישור העסקה הזה.','Buyer must accept before this time.':'הקונה חייב לאשר לפני מועד זה.','This Deal Link has expired':'פג תוקף קישור העסקה הזה'},
  hi:{'Offer valid for':'ऑफ़र की वैधता','1 day':'1 दिन','3 days':'3 दिन','7 days':'7 दिन','14 days':'14 दिन','30 days':'30 दिन','Offer active':'ऑफ़र सक्रिय है','Offer expires':'ऑफ़र समाप्त होगा','Expired':'समाप्त','expired':'समाप्त','Deal Link expired':'डील लिंक समाप्त हो गया','This Deal Link can no longer be accepted.':'इस डील लिंक को अब स्वीकार नहीं किया जा सकता।','Buyer must accept before this time.':'खरीदार को इस समय से पहले स्वीकार करना होगा।','This Deal Link has expired':'यह डील लिंक समाप्त हो गया है'}
};
Object.entries(expiryLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const titleValidationLabels:Record<string,Record<string,string>>={
  en:{'Item title must contain 3 to 120 characters.':'Item title must contain 3 to 120 characters.'},
  ka:{'Item title must contain 3 to 120 characters.':'ნივთის დასახელება უნდა შეიცავდეს 3-დან 120 სიმბოლომდე.'},
  de:{'Item title must contain 3 to 120 characters.':'Der Artikeltitel muss 3 bis 120 Zeichen enthalten.'},
  es:{'Item title must contain 3 to 120 characters.':'El título del artículo debe tener entre 3 y 120 caracteres.'},
  fr:{'Item title must contain 3 to 120 characters.':'Le titre de l’article doit contenir entre 3 et 120 caractères.'},
  pt:{'Item title must contain 3 to 120 characters.':'O título do artigo deve ter entre 3 e 120 caracteres.'},
  it:{'Item title must contain 3 to 120 characters.':'Il titolo dell’articolo deve contenere da 3 a 120 caratteri.'},
  ru:{'Item title must contain 3 to 120 characters.':'Название товара должно содержать от 3 до 120 символов.'},
  tr:{'Item title must contain 3 to 120 characters.':'Ürün başlığı 3 ile 120 karakter arasında olmalıdır.'},
  el:{'Item title must contain 3 to 120 characters.':'Ο τίτλος του αντικειμένου πρέπει να περιέχει από 3 έως 120 χαρακτήρες.'},
  zh:{'Item title must contain 3 to 120 characters.':'商品标题必须包含 3 到 120 个字符。'},
  ja:{'Item title must contain 3 to 120 characters.':'商品タイトルは3文字以上120文字以内で入力してください。'},
  ko:{'Item title must contain 3 to 120 characters.':'상품 제목은 3자 이상 120자 이하여야 합니다.'},
  ar:{'Item title must contain 3 to 120 characters.':'يجب أن يتراوح عنوان العنصر بين 3 و120 حرفًا.'},
  he:{'Item title must contain 3 to 120 characters.':'כותרת הפריט חייבת להכיל בין 3 ל-120 תווים.'},
  hi:{'Item title must contain 3 to 120 characters.':'वस्तु का शीर्षक 3 से 120 अक्षरों के बीच होना चाहिए।'}
};
Object.entries(titleValidationLabels).forEach(([code,labels])=>{dictionaries[code]={...dictionaries[code],...labels}});
const applyDocumentLanguage=(language:AppLanguage)=>{document.documentElement.lang=language;document.documentElement.dir=language==='ar'||language==='he'?'rtl':'ltr'};
applyDocumentLanguage(activeLanguage);

export function getAppLanguage(){return activeLanguage}
export function setAppLanguage(language:AppLanguage){activeLanguage=language;localStorage.setItem(languageKey,language);applyDocumentLanguage(language)}
export function t(text:string){return dictionaries[activeLanguage]?.[text]||text}
