import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, BadgeCheck, CalendarDays, Check, Copy, FileSignature, Link2, LockKeyhole, MapPin, Plus, ShieldCheck, Star } from 'lucide-react';
import { demoRepository } from './services/demoRepository';
import { acceptPublicDeal, checkSupabaseConnection, completeHandoff, confirmMeeting, createUserDeal, generateHandoffPin, getDealMeeting, getMyProfileSummary, getPublicDeal, getStoredSession, isSupabaseConfigured, listUserDeals, markArrived, proposeMeeting, signIn, signOut, signUp, submitRating, uploadDealPhotos, type DealMeeting, type ProfileSummary, type StoredSession } from './services/supabaseRest';
import type { Deal, DealDraft } from './domain';
import './styles.css';

type View = 'home' | 'create' | 'deal' | 'auth' | 'profile';
const initial: DealDraft = {title:'',description:'',price:'',condition:'Good',serialNumber:'',deliveryMethod:'Meet in person'};

function MeetingPanel({deal,session}:{deal:Deal;session:StoredSession}){
  const [meeting,setMeeting]=useState<DealMeeting|null>(null);const [form,setForm]=useState({locationName:'',address:'',scheduledAt:''});const [message,setMessage]=useState('');
  useEffect(()=>{getDealMeeting(session,deal.id).then(setMeeting).catch(()=>{})},[deal.id,session]);
  const propose=async(e:React.FormEvent)=>{e.preventDefault();setMessage('');try{await proposeMeeting(session,deal.id,form.locationName,form.address,form.scheduledAt);const next=await getDealMeeting(session,deal.id);setMeeting(next);setMessage('Meeting proposal sent to the other party.')}catch(error){setMessage(error instanceof Error?error.message:'Could not propose meeting')}};
  const confirm=async()=>{setMessage('');try{await confirmMeeting(session,deal.id);const next=await getDealMeeting(session,deal.id);setMeeting(next);setMessage('Meeting confirmed.')}catch(error){setMessage(error instanceof Error?error.message:'Could not confirm meeting')}};
  return <section className="meeting-panel"><div className="meeting-title"><CalendarDays/><div><p className="eyebrow">Safe handoff</p><h2>Plan the meeting</h2></div></div>{meeting?<div className="meeting-summary"><div><MapPin/><span><b>{meeting.location_name}</b><small>{meeting.address}</small></span></div><div><CalendarDays/><span><b>{new Date(meeting.scheduled_at).toLocaleString()}</b><small className={`meeting-status ${meeting.status}`}>{meeting.status}</small></span></div>{meeting.status==='proposed'&&meeting.proposed_by!==session.user.id&&<button className="primary" onClick={confirm}>Confirm meeting</button>}{meeting.status==='proposed'&&meeting.proposed_by===session.user.id&&<p>Waiting for the other party to confirm.</p>}</div>:<form onSubmit={propose}><label>Public meeting place<input required placeholder="Police safe exchange zone or busy café" value={form.locationName} onChange={e=>setForm({...form,locationName:e.target.value})}/></label><label>Address<input required placeholder="Street address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Date and time<input required type="datetime-local" value={form.scheduledAt} onChange={e=>setForm({...form,scheduledAt:e.target.value})}/></label><button className="primary">Propose meeting</button></form>}{message&&<div className="notice">{message}</div>}<p className="meeting-safety"><ShieldCheck/> Prefer a staffed, well-lit public location. Never share a home address by default.</p></section>
}

function HandoffPanel({deal,session,onComplete}:{deal:Deal;session:StoredSession;onComplete:()=>void}){
  const [meeting,setMeeting]=useState<DealMeeting|null>(null);const [pin,setPin]=useState('');const [sellerPin,setSellerPin]=useState('');const [message,setMessage]=useState('');
  const reload=()=>getDealMeeting(session,deal.id).then(setMeeting).catch(()=>{});useEffect(()=>{reload()},[deal.id,session]);
  if(!meeting||meeting.status!=='confirmed')return null;
  const myArrived=deal.viewerRole==='seller'?meeting.seller_arrived:meeting.buyer_arrived;
  const arrive=async()=>{try{await markArrived(session,deal.id);await reload();setMessage('Arrival recorded.')}catch(e){setMessage(e instanceof Error?e.message:'Could not record arrival')}};
  const makePin=async()=>{try{setSellerPin(await generateHandoffPin(session,deal.id));setMessage('Show this PIN only after the buyer inspects the item.')}catch(e){setMessage(e instanceof Error?e.message:'Could not generate PIN')}};
  const finish=async()=>{try{await completeHandoff(session,deal.id,pin);setMessage('Item receipt confirmed. Deal completed.');onComplete()}catch(e){setMessage(e instanceof Error?e.message:'Could not complete deal')}};
  return <section className="handoff-panel"><p className="eyebrow">In-person handoff</p><h2>Complete the exchange safely</h2><div className="arrival-grid"><div className={meeting.seller_arrived?'done':''}><Check/><span>Seller arrived</span></div><div className={meeting.buyer_arrived?'done':''}><Check/><span>Buyer arrived</span></div></div>{!myArrived&&<button className="primary" onClick={arrive}>I arrived</button>}{meeting.seller_arrived&&meeting.buyer_arrived&&deal.viewerRole==='seller'&&<div className="pin-box">{sellerPin?<><small>One-time handoff PIN</small><strong>{sellerPin}</strong></>:<button className="primary" onClick={makePin}>Generate handoff PIN</button>}</div>}{meeting.seller_arrived&&meeting.buyer_arrived&&deal.viewerRole==='buyer'&&<div className="pin-entry"><label>Enter seller’s 6-digit PIN<input inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))}/></label><button className="primary" disabled={pin.length!==6} onClick={finish}>Confirm item received</button></div>}{message&&<div className="notice">{message}</div>}<p className="meeting-safety"><ShieldCheck/> Inspect the item before sharing or entering the PIN.</p></section>
}

function RatingPanel({deal,session}:{deal:Deal;session:StoredSession}){const [stars,setStars]=useState(5);const [comment,setComment]=useState('');const [message,setMessage]=useState('');const send=async(e:React.FormEvent)=>{e.preventDefault();try{await submitRating(session,deal.id,stars,comment);setMessage('Thank you. Your rating was saved.')}catch(error){setMessage(error instanceof Error?error.message:'Could not save rating')}};return <section className="rating-panel"><Star/><div><p className="eyebrow">Deal completed</p><h2>Rate the other party</h2><form onSubmit={send}><label>Rating<select value={stars} onChange={e=>setStars(Number(e.target.value))}><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Okay</option><option value="2">2 — Poor</option><option value="1">1 — Very poor</option></select></label><label>Comment<textarea maxLength={500} value={comment} onChange={e=>setComment(e.target.value)} placeholder="What went well?"/></label><button className="primary">Submit rating</button></form>{message&&<div className="notice">{message}</div>}</div></section>}

function App() {
  const initialSession=getStoredSession();
  const [view,setView]=useState<View>('home'); const [deals,setDeals]=useState<Deal[]>([]); const [active,setActive]=useState<Deal>(); const [draft,setDraft]=useState(initial); const [buyer,setBuyer]=useState('');
  const [databaseConnected,setDatabaseConnected]=useState(false);
  const [session,setSession]=useState<StoredSession|null>(initialSession);
  const user=session?.user??null;
  const [authMode,setAuthMode]=useState<'signin'|'signup'>('signup');
  const [authForm,setAuthForm]=useState({displayName:'',email:'',password:''});
  const [authMessage,setAuthMessage]=useState('');
  const [photos,setPhotos]=useState<File[]>([]);
  const [profile,setProfile]=useState<ProfileSummary|null>(null);
  useEffect(()=>{if(session){listUserDeals(session).then(setDeals).catch(()=>setDeals([]))}else{demoRepository.list().then(setDeals)}},[session]);
  useEffect(()=>{if(isSupabaseConfigured) checkSupabaseConnection().then(setDatabaseConnected)},[]);
  useEffect(()=>{const publicId=new URLSearchParams(location.search).get('deal');if(publicId){getPublicDeal(publicId).then(deal=>{setActive(deal);setView('deal')}).catch(error=>setAuthMessage(error instanceof Error?error.message:'Deal Link unavailable'))}},[]);
  const create=async(e:React.FormEvent)=>{e.preventDefault();if(!session)return;setAuthMessage('');try{let deal=await createUserDeal(session,draft);if(photos.length){const mediaUrls=await uploadDealPhotos(session,deal.id,photos);deal={...deal,mediaUrls}}setDeals(x=>[deal,...x]);setActive(deal);setDraft(initial);setPhotos([]);setView('deal')}catch(error){setAuthMessage(error instanceof Error?error.message:'Could not save this deal')}};
  const open=(d:Deal)=>{setActive(d);setView('deal')};
  const accept=async()=>{if(!active||!buyer.trim())return;if(!session){setAuthMessage('Sign in or create an account to accept this deal.');setView('auth');return}try{await acceptPublicDeal(session,active.publicId,buyer.trim());const deal={...active,status:'accepted' as const,buyerName:buyer.trim(),buyerVerification:'not_started' as const,viewerRole:'buyer' as const};setActive(deal);setDeals(x=>x.map(d=>d.id===deal.id?deal:d))}catch(error){setAuthMessage(error instanceof Error?error.message:'Could not accept this deal')}};
  const openCreate=()=>{if(!user){setView('auth');return}setView('create')};
  const submitAuth=async(e:React.FormEvent)=>{e.preventDefault();setAuthMessage('');try{if(authMode==='signup'){const result=await signUp(authForm.email,authForm.password,authForm.displayName);if(result.session){setSession(result.session);setView('home')}else setAuthMessage('Check your email to confirm your account, then sign in.')}else{const nextSession=await signIn(authForm.email,authForm.password);setSession(nextSession);setView('home')}}catch(error){setAuthMessage(error instanceof Error?error.message:'Something went wrong')}};
  const logout=()=>{signOut();setSession(null);setView('home')};
  const openProfile=async()=>{if(!session)return;setAuthMessage('');setView('profile');try{setProfile(await getMyProfileSummary(session))}catch(error){setAuthMessage(error instanceof Error?error.message:'Could not load profile')}};

  return <div className="app">
    <header><button className="brand" onClick={()=>setView('home')}><span><ShieldCheck size={20}/></span>DealSafe</button><span className={`beta ${databaseConnected?'connected':''}`}>{databaseConnected?'Database connected':'Private beta'}</span><div className="account">{user?<><button onClick={openProfile}>{user.displayName}</button><button onClick={logout}>Sign out</button></>:<button onClick={()=>setView('auth')}>Sign in</button>}</div></header>
    <main>
      {view==='create'&&<section className="media-picker"><label>Item photos<input className="file-input" type="file" accept="image/jpeg,image/png,image/webp,image/heic" capture="environment" multiple onChange={e=>setPhotos(Array.from(e.target.files||[]).slice(0,6))}/><small>Up to 6 photos · 6 MB each · JPG, PNG, WebP or HEIC</small></label>{photos.length>0&&<div className="photo-previews">{photos.map((file,index)=><div key={`${file.name}-${index}`}><img src={URL.createObjectURL(file)} alt={`Preview ${index+1}`}/><span>{index===0?'Main photo':`Photo ${index+1}`}</span></div>)}</div>}</section>}
      {view==='deal'&&active?.mediaUrls?.length&&<section className="public-gallery"><div className="deal-gallery">{active.mediaUrls.map((url,index)=><img key={url} className={index===0?'main-photo':''} src={url} alt={`${active.title} photo ${index+1}`}/>)}</div></section>}
      {view==='deal'&&active&&session&&active.status==='accepted'&&active.viewerRole!=='visitor'&&<MeetingPanel deal={active} session={session}/>} 
      {view==='deal'&&active&&session&&active.status==='accepted'&&active.viewerRole!=='visitor'&&<HandoffPanel deal={active} session={session} onComplete={()=>setActive({...active,status:'completed'})}/>} 
      {view==='deal'&&active&&session&&active.status==='completed'&&active.viewerRole!=='visitor'&&<RatingPanel deal={active} session={session}/>} 
      {view==='home'&&<>
        <section className="hero"><div><p className="eyebrow">A clearer way to make a private sale</p><h1>Put the deal in writing.<br/>Share it with confidence.</h1><p className="lede">Create a single link with the item, price, parties, and agreed terms—before money or goods change hands.</p><button className="primary" onClick={openCreate}><Plus size={18}/>Create a Deal Link</button><p className="micro"><LockKeyhole size={14}/> DealSafe does not hold your money in this beta.</p></div><div className="phone"><div className="phone-top">dealsafe.link/DS-7K4M2Q</div><div className="phone-body"><div className="safe"><BadgeCheck/> Seller contact verified</div><h3>iPhone 15 Pro · 256 GB</h3><strong>$780.00</strong><div className="fake-photo">15 <small>PRO</small></div><div className="fact"><span>Condition</span><b>Good</b></div><div className="fact"><span>Handoff</span><b>Meet in person</b></div><button className="dark">Review agreement</button></div></div></section>
        <section className="trust"><h2>One link. The facts that matter.</h2><div className="features"><article><Link2/><h3>Shared terms</h3><p>Price, condition, handoff, and disclosures stay together.</p></article><article><BadgeCheck/><h3>Clear verification</h3><p>See exactly which contact or identity checks are complete.</p></article><article><FileSignature/><h3>Recorded consent</h3><p>Both parties accept the same version of the agreement.</p></article></div></section>
        <section className="dashboard"><div className="section-head"><div><p className="eyebrow">Your workspace</p><h2>Recent deals</h2></div><button className="secondary" onClick={openCreate}><Plus size={16}/>New deal</button></div>{deals.map(d=><button className="deal-row" key={d.id} onClick={()=>open(d)}><span className="deal-icon">{d.title.slice(0,1)}</span><span><b>{d.title}</b><small>{d.publicId} · {d.condition}</small></span><em>${(d.priceCents/100).toFixed(2)}</em><span className={`status ${d.status}`}>{d.status}</span><ArrowRight size={18}/></button>)}</section>
      </>}
      {view==='profile'&&<section className="profile-page"><button className="back" onClick={()=>setView('home')}>← Dashboard</button><p className="eyebrow">Trust profile</p><h1>{profile?.display_name||user?.displayName}</h1>{authMessage&&<div className="notice">{authMessage}</div>}{profile&&<><div className="profile-stats"><article><span>Average rating</span><strong>{profile.average_rating??'—'} <Star size={22}/></strong><small>{profile.rating_count} received</small></article><article><span>Completed deals</span><strong>{profile.completed_deals}</strong><small>Successful handoffs</small></article><article><span>Verification</span><strong className="verification-value"><BadgeCheck size={22}/>{profile.verification_status.replace('_',' ')}</strong><small>Identity verification comes next</small></article></div><div className="profile-details"><h2>Reputation history</h2><p>Member since {new Date(profile.member_since).toLocaleDateString()}</p>{profile.recent_ratings.length?<div className="review-list">{profile.recent_ratings.map((rating,index)=><article key={`${rating.created_at}-${index}`}><div>{'★'.repeat(rating.stars)}{'☆'.repeat(5-rating.stars)}</div><p>{rating.comment||'No written comment.'}</p><small>{new Date(rating.created_at).toLocaleDateString()}</small></article>)}</div>:<div className="empty-state"><Star/><b>No ratings yet</b><span>Ratings received after completed deals will appear here.</span></div>}</div></>}</section>}
      {view==='auth'&&<section className="form-wrap auth-wrap"><button className="back" onClick={()=>setView('home')}>← Back</button><p className="eyebrow">DealSafe account</p><h1>{authMode==='signup'?'Create your account':'Welcome back'}</h1><form onSubmit={submitAuth}>{authMode==='signup'&&<label>Your name<input required placeholder="Alex Morgan" value={authForm.displayName} onChange={e=>setAuthForm({...authForm,displayName:e.target.value})}/></label>}<label>Email<input required type="email" placeholder="you@example.com" value={authForm.email} onChange={e=>setAuthForm({...authForm,email:e.target.value})}/></label><label>Password<input required minLength={8} type="password" placeholder="At least 8 characters" value={authForm.password} onChange={e=>setAuthForm({...authForm,password:e.target.value})}/></label>{authMessage&&<div className="notice">{authMessage}</div>}<button className="primary full">{authMode==='signup'?'Create account':'Sign in'}</button><button type="button" className="switch-auth" onClick={()=>{setAuthMode(authMode==='signup'?'signin':'signup');setAuthMessage('')}}>{authMode==='signup'?'Already have an account? Sign in':'New to DealSafe? Create account'}</button></form></section>}
      {view==='create'&&<section className="form-wrap"><button className="back" onClick={()=>setView('home')}>← Dashboard</button><p className="eyebrow">New Deal Link</p><h1>Describe what you’re selling</h1><p className="lede small">You can review every detail before the link is published.</p><form onSubmit={create}><label>Item title<input required placeholder="iPhone 15 Pro · 256 GB" value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="two"><label>Price (USD)<input required min="1" type="number" placeholder="780" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})}/></label><label>Condition<select value={draft.condition} onChange={e=>setDraft({...draft,condition:e.target.value as DealDraft['condition']})}><option>Like new</option><option>Good</option><option>Fair</option></select></label></div><label>Known condition and defects<textarea required placeholder="Be specific about wear, repairs, locks, and included accessories." value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label>Serial or IMEI (optional)<input placeholder="Stored privately; only last characters shown" value={draft.serialNumber} onChange={e=>setDraft({...draft,serialNumber:e.target.value})}/></label><label>Handoff<select value={draft.deliveryMethod} onChange={e=>setDraft({...draft,deliveryMethod:e.target.value as DealDraft['deliveryMethod']})}><option>Meet in person</option><option>Ship to buyer</option></select></label><div className="notice"><ShieldCheck/><span><b>Next in production:</b> add photos, verify contact, then preview the agreement. This prototype publishes immediately.</span></div><button className="primary full">Publish Deal Link <ArrowRight size={18}/></button></form></section>}
      {view==='deal'&&active&&<section className="deal-page"><button className="back" onClick={()=>setView('home')}>← Dashboard</button><div className="deal-grid"><div><div className="safe"><BadgeCheck/> Seller contact {active.sellerVerification}</div><p className="eyebrow">Deal {active.publicId}</p><h1>{active.title}</h1><div className="price">${(active.priceCents/100).toFixed(2)}</div><div className="product-art">{active.title.slice(0,1)}<small>Photo placeholder</small></div><h2>Item details</h2><p>{active.description}</p><div className="facts"><div><span>Condition</span><b>{active.condition}</b></div><div><span>Handoff</span><b>{active.deliveryMethod}</b></div><div><span>Serial</span><b>{active.serialNumber||'Not provided'}</b></div></div></div><aside><div className="agreement"><FileSignature/><h2>Deal agreement</h2><p>Version {active.agreementVersion} · The buyer agrees to the stated price, condition disclosures, and handoff method.</p><ul><li><Check/>Item and defects reviewed</li><li><Check/>Price confirmed</li><li><Check/>Handoff terms confirmed</li></ul>{active.status==='published'?<><label>Your full name<input placeholder="Buyer name" value={buyer} onChange={e=>setBuyer(e.target.value)}/></label>{authMessage&&<div className="notice">{authMessage}</div>}<button className="primary full" onClick={accept}>Accept these terms</button><small>Typing your name records consent for this prototype. Production language requires legal review.</small></>:<div className="accepted"><BadgeCheck/><div><b>Terms accepted</b><span>{active.buyerName||'Buyer'} · verification pending</span></div></div>}</div><button className="copy" onClick={()=>navigator.clipboard?.writeText(`${location.origin}/?deal=${active.publicId}`)}><Copy size={16}/>Copy Deal Link</button><div className="rating"><Star/><span><b>Ratings unlock after completion</b><small>One rating per party, tied to this deal.</small></span></div></aside></div></section>}
    </main><footer><span>DealSafe beta</span><span>Facts, consent, and a clearer handoff.</span></footer>
  </div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
